### ISSUE TITLE
Incompatible with VS 2022 RC?

### ISSUE THREAD

**Issue by lavanyadeepak** [microsoft/dotnet-apiport#1002]
I was trying to add Portability Analyzer to my VS 2022 RC and it refused with this message

![image](https://user-images.githubusercontent.com/2217926/138394772-6118d28e-3113-42f4-9f31-af51238b3711.png)

**Comment by dcrider-risas** [comment]
@Lxiamail Any timeline on when it will support VS2022?

**Comment by prabhatkk** [comment]
Are there any plans to support the  Portability Analyzer extension on VS 2022?

**Comment by tudor-turcu** [comment]
This project seems dead - no new releases in the last two years.. I don't know if there is a newer alternative..

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
