### ISSUE TITLE
Report falsely claims target types are not supported when they *are*

### ISSUE THREAD

**Issue by AArnott** [microsoft/dotnet-apiport#1005]
Running APIPort against at least one directory of assemblies produced a report of 17 incompatibilities, but every single one is a false positive. Here are the groupings of APIs that apiport apparently is ignorant of being available on .NET 5:

- MSBuild (T:Microsoft.Build.Utilities.TaskLoggingHelper)
- MEFv1 (T:System.ComponentModel.Composition.AttributedModelServices)
- ADO.NET? (T:System.Data.SqlClient.SqlConnection)
- WPF (T:System.Windows.Controls.VirtualizingStackPanel)

**Comment by twsouthwick** [comment]
What target framework are you comparing against? If I remember correctly, the platform extensions would include Windows specific (and hopefully WPF stuff). Not sure if that would explain all of the missing types, though.

**Comment by AArnott** [comment]
I was using ".NET, Version=5.0" at the time. 
When I use ".NET + Platform Extensions, Version=5.0" MSBuild and WinForms types still show up as incompatible, though I didn't see MEFv1 or ADO.NET any more (although maybe I just missed them for all the other noise and valid APIs that were listed.)

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
