### ISSUE TITLE
./init.ps1 fails on feed https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/

### ISSUE THREAD

**Issue by DarwinJS** [microsoft/dotnet-apiport#1007]
When I run init.ps1 I get many package restore failures from https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/

I've tried creating and adding a token.

I have tried removing the existing urls and adding https://pkgs.dev.azure.com/dnceng/public/_packaging/3.1.415-servicing-015859-shipping-1/nuget/v3/index.json or https://pkgs.dev.azure.com/dnceng/public/_packaging/nuget/v3/index.json

I am doing this on a dotnet SDK linux container and I've tried the following:
- mcr.microsoft.com/dotnet/sdk:2.1
- mcr.microsoft.com/dotnet/sdk:3.1
- mcr.microsoft.com/dotnet/sdk:6.0

I had this working on linux some months back with version 2.1 of the SDK and the project still included a build.sh script, which is still referenced here: https://github.com/microsoft/dotnet-apiport/blob/dev/docs/Console/README.md#run-the-tool-in-an-offline-mode

This line also references a file that no longer seems to be in the repository: https://github.com/microsoft/dotnet-apiport/blob/dev/init.ps1#L83

Is the project's nuget restores properly mapped to public nuget feeds?

If this is no longer buildable under linux as mentioned in another issue - it is quite unclear in the docs.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
