### ISSUE TITLE
here was an unknown error code from the service: 'InternalServerError'.

### ISSUE THREAD

**Issue by Robbbbin0309** [microsoft/dotnet-apiport#1019]
I 'm getting this error both on vs and console, output file is selected to be json and excel. Any advice?
![image](https://user-images.githubusercontent.com/110597303/183012019-5076f41c-f88b-47de-be67-c14bf3f33df2.png)
![image](https://user-images.githubusercontent.com/110597303/183012029-b910b46a-0f03-4759-bbdf-147f72b77c74.png)
![image](https://user-images.githubusercontent.com/110597303/183012537-d7359f8a-9333-4488-a102-647942849385.png)

Which really confused me is that I just ran it successfully yesterday, and I didn't do much of anything except running the .Net upgrade assistant to the same project on vs2022 since the last time it worked.

**Comment by Dixie234** [comment]
I am getting same issue as @Robbbbin0309. Worked fine the other day, but this morning receiving same error.

**Comment by jbstans** [comment]
Same issue here, problems since Thursday 4th. I'm presuming it's to do with the service getting deprecated, but uncertain.

**Comment by StuartSiegel** [comment]
The tool ran fine on 8/3/2022. When attempting to run it last week (Aug 4th & 5th) and today Monday, Aug 8th, 2022 it fails. It fails using the command line via the extension in Visual Studio 2019.

![image](https://user-images.githubusercontent.com/110849108/183488201-e825551d-52c5-4ea0-a546-a34630346ea4.png)

When using Fiddler Anywhere it show's there's a 500 Internal Server Error
![image](https://user-images.githubusercontent.com/110849108/183488636-d870a807-5210-4c25-89c1-61f203effabd.png)

Fiddler shows it is trying to reach host 104.214.29.203.
![image](https://user-images.githubusercontent.com/110849108/183489734-3322b681-9188-458f-83fa-afb2bd1076ee.png)


**When I attempt to ping 104.214.29.203 I get no response.**
![image](https://user-images.githubusercontent.com/110849108/183489765-715ec0b0-1e78-4dec-83d4-cf5bb596c139.png)

**Comment by jbparker** [comment]
Same issue as all of the above.
