### ISSUE TITLE
ApiPort fails with the message - There was an unknown error while reaching the service

### ISSUE THREAD

**Issue by venknar** [Microsoft/dotnet-apiport#102]
Trying to run the Apiport.exe -listTargets. It runs and then fails with the message;

Microsoft (R) API Portability Analyzer v1.0.251.0
Copyright (C) Microsoft Corporation. All rights reserved.

To learn more about how this tool works, including the data we are collecting, go here - http://go.microsoft.com/fwlink/?LinkId=397652

Retrieving targets                                [Failed]

There was an unknown error attempting to reach the service.  Please try again.

Some reason the service is not reachable and it fails. I downloaded the Apiport from http://www.microsoft.com/en-us/download/details.aspx?id=42678

**Comment by conniey** [comment]
I could not reproduce the error you are seeing. Can you try again? (I used the internal version you used and tried it out with the 1.0.0-alpha version as well.)

**Comment by venknar** [comment]
Issue is resolved. Some proxy settings issues in my machine.
Thanks
