### ISSUE TITLE
Unknown error code from the service: 'InternalServerError'. Fiddler shows host 104.214.20.203. Ping server and get no resposne

### ISSUE THREAD

**Issue by StuartSiegel** [microsoft/dotnet-apiport#1020]
Trying to use the Portability Analyzier. It ran last week on Monday 8/3/2022. Now it's not working. It gives an error in VS2019
![image](https://user-images.githubusercontent.com/110849108/183491092-d1b451d6-d6da-4b46-927e-5e276e41c70d.png)

When using Fiddler it shows trying to reach host 104.214.20.203
![image](https://user-images.githubusercontent.com/110849108/183491390-cd8fffe0-1632-44b5-bee5-c14e0d90e447.png)

When I try to ping 104.214.29.203 I get no response:
![image](https://user-images.githubusercontent.com/110849108/183491484-0325d641-59ce-4b3d-8abf-e3b6176bf8f0.png)

![image](https://user-images.githubusercontent.com/110849108/183491822-d43097b0-28b1-470f-a9c9-f119399be733.png)

**Comment by mbalatha** [comment]
Still we are getting the same error, here `"There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version."`

**Comment by alexander-lysenko-88** [comment]
I'm also getting the `InternalServerError` since Friday August 5.
looks like issues is related to `POST https://portability.dot.net/api/analyze` endpoint which responds with `500` status code

**Comment by jbparker** [comment]
Reporting the same error as above for solidarity.

**Comment by alexander-lysenko-88** [comment]
Although the issue is marked as closed it still reproduces. So please reopen it.

**Comment by brandonh-msft** [comment]
did you download the new VSIX?

**Comment by alexander-lysenko-88** [comment]
My bad. I checked via VS Extensions Manager and it said that I was up to date. But now I see on the site (https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer) that a new version was released yesterday. Probably some cache issue. I'll give it a try!

**Comment by alexander-lysenko-88** [comment]
new version (2.8.48.15310) works fine 👍

**Comment by brandonh-msft** [comment]
> new version (2.8.48.15310) works fine 👍

Thanks for letting us know!
