### ISSUE TITLE
Track how many times a flagged API is used

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/dotnet-apiport#103]

**Comment by AlexGhiondea** [comment]
This would be nice, but it requires parsing the method body IL which will definitively have a perf impact.

Consider using the method body parsing from this library: https://github.com/dotnet/corefxlab/tree/master/src/System.Reflection.Metadata.Cil

**Comment by conniey** [comment]
This would be nice to have for post processing (check against APIs that are not supported).

**Comment by conniey** [comment]
Large architectural change, will revisit if there is a large ask for this feature.
