### ISSUE TITLE
Correct the Mono version shown in listTargets

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/dotnet-apiport#144]
The version we are displaying is the equivalent .NET version, not the Mono. This needs to be fixed.

**Comment by akoeplinger** [comment]
From https://github.com/Microsoft/dotnet-apiport/pull/143#discussion_r39667774
> Can you put some info on that issue as to how to determine which version of Mono we have (we have a drop of the assemblies that are indexed for the service)?

If you just have the BCL assemblies I think it's impossible to get the Mono version they shipped with. Having looked at it, only mcs.exe sets its AssemblyVersion to the Mono version so you might be able to use that.

**Comment by twsouthwick** [comment]
I took a look at the mcs.exe and the FileVersion and AssemblyVersion are 3.3.0.0. Does that sound right?

**Comment by akoeplinger** [comment]
Yes, though these are 1.5yrs old files then, you might consider updating to newer a Mono version :)

I'm a bit surprised that the 2.0 mcs.exe has 2.10.9 as that'd be even older, are you sure they're from the same drop?

**Comment by twsouthwick** [comment]
When I examine the 3 drops, I get the following:

| Our label | mcs.exe version |
|----|-----|
| 2.0 | 2.10.9|
| 4.0 | [no mcs.exe] |
| 4.5 | 3.3.0.0 |

If it's that old, we should definitely update it. Is there a way we can just get a drop of it, or do we need to install it?

**Comment by akoeplinger** [comment]
The easiest way is probably to download the MSI from http://www.mono-project.com/download/#download-win and extract it using the usual tools you find on the internet.

**Comment by twsouthwick** [comment]
The Mono version is now updated to reflect 3.3.0.0. I'll open another issue to track getting an updated version.
