### ISSUE TITLE
In addition to percentages provide number of errors per assembly

### ISSUE THREAD

**Issue by danroth27** [Microsoft/dotnet-apiport#153]
If you have a small assembly the percentage can be misleading. It would be great to also show the number of errors per assembly in the generated report.

**Comment by twsouthwick** [comment]
Can you give more detail? An example of what is currently displayed and what would be more helpful would be great.

**Comment by danroth27** [comment]
The generated spreadsheet shows the list of assemblies analyzed and a percentage for how compatible the assembly is. But some assemblies are bigger than others. It would be useful to also show the number of errors in addition to the percentage.

**Comment by conniey** [comment]
Duplicate of #103
