### ISSUE TITLE
Use recommended changes from containing APIs

### ISSUE THREAD

**Issue by terrajobst** [Microsoft/dotnet-apiport#155]
When looking for recommended changes at the member level, API port should fall back to the recommended changes at the chain of containing types, up to, and including the namespaces.

This makes it a lot easier for us to have a complete list of recommendations without having to add them to each and every member.

So when looking for recommendations of  `System.Runtime.Awesome.Type.Subtype.Member`, it should probe in the following order:

1. `M:System.Runtime.Awesome.Type.Subtype.Member`
2. `T:System.Runtime.Awesome.Type.Subtype`
3. `T:System.Runtime.Awesome.Type`
4. `N:System.Runtime.Awesome`
5. `N:System.Runtime`
6. `N:System`

**Comment by richlander** [comment]
Nice idea.

**Comment by terrajobst** [comment]
Excellent. Thanks!
