### ISSUE TITLE
Add new Mono version to available targets

### ISSUE THREAD

**Issue by twsouthwick** [microsoft/dotnet-apiport#156]
The Mono version we have available on ApiPort (3.3.0.0) is out of date. See #144 of some more discussion of this. An updated version is available here: http://www.mono-project.com/download/#download-win

**Comment by conniey** [comment]
@terrajobst What is the current version of Mono?

**Comment by rjvdboon** [comment]
According to http://www.mono-project.com/download/#download-win the current mono release is 5.4.1.6. The current cadence seems to be a new mono release every 2 months.
And with each release they are improving .Net standard 2.0 compatibility and conformance to .net 4.7.x.

**Comment by Lxiamail** [comment]
Fixed.
