### ISSUE TITLE
Assembly is skipped in report depending on order of input

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/dotnet-apiport#175]
Scenario: c.dll has a reference on b.dll

```
ApiPort.exe -f a.dll -f b.dll -f c.dll
```

b.dll would not show up in report. It would show up with the following order:

```
ApiPort.exe -f a.dll -f b.dll -f c.dll -f b.dll
```

Notice the duplication of b.dll (or that b.dll is listed after c.dll)

**Comment by conniey** [comment]
Confirm that this is a bug still.

**Comment by alinapopa** [comment]
The issue no longer reproduces.
