### ISSUE TITLE
Add API search support to dotnetstatus site

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/dotnet-apiport#181]
Right now there is a "search" box with autocomplete.  If you type (or use autocomplete to get) the full name of the API, then you can navigate to the page for that API.  But there's no search results page and no way to search using a partial name.

We should:

- Add a search results page
- Support searching for partial names
- Show types in the search results in addition to members

**Comment by conniey** [comment]
This issue was moved to Microsoft/dotnet-apiweb#19
