### ISSUE TITLE
API details page should make it easy to add / edit recommended changes

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/dotnet-apiport#183]
If I look up an API that's not available on .NET Core and it doesn't have any recommended changes, I should be able to easily add information about what to replace it with.  Ideally the recommended changes would be stored in a GitHub repo, and the API details page could include a link that would start a pull request to add recommended changes for the API.

**Comment by conniey** [comment]
This issue was moved to Microsoft/dotnet-apiweb#18
