### ISSUE TITLE
Create Roslyn analyzers to help apply direct API replacements when porting to .NET Core

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/dotnet-apiport#184]
Create Roslyn analyzers to help with repetitive API changes when porting to .NET Core, such as:
- Close -> Dispose
- Thread.CurrentCulture -> CultureInfo.CurrentCulture
- Add a call to GetTypeInfo() when necessary

**Comment by conniey** [comment]
A lot of the fixes will not be needed after .NET Standard 2.0.
