### ISSUE TITLE
Don't show items that just have source compatibility

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/dotnet-apiport#205]
If an item is source compatible, that should be considered a no-op from a porting perspective. Thus, we shouldn't expose that in reports.

**Comment by conniey** [comment]
Double-checked, I think this should be fixed.

**Comment by conniey** [comment]
We have this fixed here: https://github.com/Microsoft/dotnet-apiport/blob/master/src/Microsoft.Fx.Portability/Analysis/AnalysisEngine.cs#L249
