### ISSUE TITLE
Update HTML reporter to work on core

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/dotnet-apiport#218]
There are two changes needed here:
- Right now, we are using an earlier version of RazorEngine that does not work on core.
- ~~The markdown parser we are using is actually targeting .NET 3.5 (seems to work, fine, though). The new project.json format won't load it, though, on 4.5 or dotnet~~

**Comment by conniey** [comment]
Fixed in: https://github.com/Microsoft/dotnet-apiport/pull/742
