### ISSUE TITLE
Consider analyzing PInvokes (DllImports)

### ISSUE THREAD

**Issue by dsplaisted** [Microsoft/dotnet-apiport#234]
APIPort is commonly used to help port code to .NET Core.  Often this is done in order to run the code on different operating systems.  DllImports/PInvokes represent calls to native code that may or may not be available on other OS's.  It would be useful if APIPort would list all the DllImports in an assembly it analyzes, to help determine whether they will need to be replaced when porting.

**Comment by conniey** [comment]
Nice to Have
