### ISSUE TITLE
Target selection on VS plugin is not very discoverable

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/dotnet-apiport#245]

**Comment by conniey** [comment]
Any suggestions on how we can make this more discoverable?

**Comment by twsouthwick** [comment]
Maybe a context menu? Right now, the only way to get to the target selection is via Tools->Options->.NET Portability Analyzer. It would be great to add a menu item next to the "Analyze assembly portability" that takes you to the options pane.

**Comment by Athari** [comment]
@conniey Having global options for all projects doesn't look like a good idea to me. I'd rather have options saved in a project file or a separate config file, and in that case, a project options tab would be appropriate and discoverable, I think.

Either way, target selection can be made available in the context menu "Project > Analyze > Choose Portability Analyzer Target Platforms", just like "Analyze Assembly Portability".

**Comment by twsouthwick** [comment]
We've added a context menu which will be available in the next release.
