### ISSUE TITLE
Console and VSIX show different percentages in report

### ISSUE THREAD

**Issue by conniey** [Microsoft/dotnet-apiport#251]
## Repro Steps
1. Generating a binary using the visual studio extension
2. Analyze that same binary using the console tool
## Expected
The reports are identical
## Actual
The percentages are different despite the results being exactly the same

![differentpercentages](https://cloud.githubusercontent.com/assets/10136526/12828399/6e09d486-cb39-11e5-99ab-44a316a7e4b2.png)

**Comment by twsouthwick** [comment]
The VSIX is currently using CCI while the command line tool is using S.R.Metadata so there may be a difference in what types/methods are being extracted.

**Comment by twsouthwick** [comment]
@conniey Do you have a repro of this?

**Comment by conniey** [comment]
Can't repro
