### ISSUE TITLE
VSIX: Output report to the project's output directory rather than its sources directory

### ISSUE THREAD

**Issue by conniey** [Microsoft/dotnet-apiport#253]
## Repro Steps
1. Open a solution
2. Right-click on a project, Analyze -> Analyze Assembly Portability

The report is generated using the artefacts of the project being analysed, so it makes more sense to see report saved to the output directory of the project rather than in the sources directory.

**Comment by twsouthwick** [comment]
Behavior for this has changed. See #359 for an updated issue.
