### ISSUE TITLE
APIPort does not detect usage of the Serializable Attribute 

### ISSUE THREAD

**Issue by DrewScoggins** [Microsoft/dotnet-apiport#257]
When running the analyzer tool on code that uses the Serializable attribute you will get a 100% pass rate for .NET Core even though it is not supported there.  It looks like we do not check for flags that are set on types, just custom attributes.

**Comment by twsouthwick** [comment]
`[Serializable]` is translated into a flag on the type instead of an attribute in the metadata. Looks like there's some helpful stuff on this Roslyn issue: https://github.com/dotnet/roslyn/issues/3898. We should be able to pull out a flag of "IsSerializable" and flag issues for that

**Comment by conniey** [comment]
Looks like a synthetic attribute should be created in Roslyn now. So we'll not worry about it for now.
