### ISSUE TITLE
Add option to collapse identical columns in HTML report

### ISSUE THREAD

**Issue by Athari** [Microsoft/dotnet-apiport#261]
Some target platforms are very similar and analysis can produce identical results for them. Viewing HTML report will be easier if such platforms are collapsed together. Also, when porting, it's helpful to see what platform-dependent code should be moved/replaced/whatever. Overall, the report will be considerably less scary if it contains less redundant information.

**Comment by twsouthwick** [comment]
This makes sense. We would love a contribution if you want to add that to the HTML report generator!

**Comment by conniey** [comment]
Nice to have, please re-open if you have a PR to submit. :)

**Comment by conniey** [comment]
There are checkboxes so you can hide columns (under "Hide columns:") if they are cumbersome to look at. I hope this fixes your issue.

![image](https://cloud.githubusercontent.com/assets/10136526/26808940/888f8362-4a15-11e7-8395-f7f20bb9cfb6.png)
