### ISSUE TITLE
A lot of reflection functionality like Type.BaseType is not available anymore in dnxcore50

### ISSUE THREAD

**Issue by StefH** [Microsoft/dotnet-apiport#268]
As known, a lot of reflection functionality like `Type.BaseType` is not available anymore in dnxcore50. A possible solution would be to use:`Type.GetTypeInfo().BaseType`.

I encountered this issue a lot while converting some of my projects.

I solved this compatibility issue by create a helper library (https://github.com/StefH/ReflectionBridge) : which functions as a bridge to some reflection functionality.

In my normal libraries, I just rewrite all calls from `Type.BaseType` to `Type.BaseType()` (so instead of invoking a property, I create an extension method like this:
```c#
        public static Type BaseType(this Type type)
        {
#if REFLECTIONBRIDGE && (!(NET40 || NET35 || NET20))
            return type.GetTypeInfo().BaseType;
#else
            return type.BaseType;
#endif
        }
```
With this new helper functionality, I don't need any **ifdefs** in my main code, this is solved in the extension method.

Are there any plans for Microsoft or another communicate to also create something like this to help porting code to dnxcore50 ?

**Comment by twsouthwick** [comment]
@StefH Did run ApiPort and get a RecommendedChange?

@weshaggard Is anything like this planned for .NET Core?

**Comment by weshaggard** [comment]
There are currently no plans to provide a bridge between <=NET40 and .NET Core. For the reflection APIs we are adding a lot of the missing ones back but there you still need to go through GetTypeInfo() like above and GetTypeInfo() only exists in NET45 and higher. So if your code is only targeting NET45 and NETCore then there shouldn't need to be any #ifdefs for this type of change.

**Comment by twsouthwick** [comment]
@StefH I'm closing this issue for now - if you didn't get a recommended change from ApiPort and you think you should, please reopen.
