### ISSUE TITLE
Suggestion for StringComparison.InvariantCultureIgnoreCase is wrong ?

### ISSUE THREAD

**Issue by StefH** [Microsoft/dotnet-apiport#271]
Suggestion is like:.

_System.StringComparer      get_InvariantCultureIgnoreCase_
Use ```CompareInfo.GetStringComparer```

However this has an error?
```D:\Projects\dotnet\Program.cs(13,46): error CS0117: 'CompareInfo' does not contain a definition for 'GetStringComparer'```

**Comment by twsouthwick** [comment]
Do you have a using for System.Globalization? If that works, we need to update the recommendation to say `Use System.Globalization.CompareInfo.GetStringComparer`

**Comment by jhofker** [comment]
`GetStringComparer` doesn't seem to exist in `System.Globalization.CompareInfo`, unless I'm doing something wrong. (Pretty likely)

In most cases I've been replacing `StringComparer.InvariantCultureIgnoreCase.Equal(...)` with `string.Equals(a, b, StringComparison.InvariantCultureIgnoreCase)` and that's fine, but I have a couple uses inside linq like `(...).Distinct(StringComparer.InvariantCultureIgnoreCase)` that are a bit tougher.

**Comment by twsouthwick** [comment]
Ah - looks like it is in the `System.Globalization.Extensions` package. Let me know if that works - if it does, we'll update the recommendation.

**Comment by twsouthwick** [comment]
The site http://packagesearch.azurewebsites.net/ provides a nice way to find where methods/types are. Search for `GetStringComparer` and it will tell you which package to install.

**Comment by StefH** [comment]
The `GetStringComparer` is not static method on the `CompareInfo` class, but an **extension** method on the `CompareInfo` class?

See source code here:
https://github.com/dotnet/corefx/blob/master/src/System.Globalization.Extensions/src/System/Globalization/Extensions.cs

**Comment by conniey** [comment]
I think this is what it means:
```csharp
using System;
using System.Globalization;

namespace Test
{
    public class Class1
    {
        public StringComparer GetComparer()
        {
            var comparer = CultureInfo.InvariantCulture.CompareInfo.GetStringComparer(CompareOptions.IgnoreCase);

            return comparer;
        }
    }
}
```

**Comment by jhofker** [comment]
Thanks everyone!

**Comment by twsouthwick** [comment]
I've added a PR to fix the recommendation. @jhofker would the message I replaced it with have unblocked you?

**Comment by jhofker** [comment]
Looks great, thank you!
