### ISSUE TITLE
API Port flags compiler generated code in portable class libraries

### ISSUE THREAD

**Issue by mtaron** [microsoft/dotnet-apiport#273]
Hi, I'm trying out API Port on one of my project and noticed that it was flagging some compiler generated code. A simple repro:
1. Create a new Portable Class Library (I did C#, .NET Framework 4.6, Windows Universal 10.0).
2. Add a new Resource File (.resx).
3. Build.
4. Run API Port.

It flags the compiler generated ResourceManager property as a portability issue. Is this is a problem?

**Comment by conniey** [comment]
This is a known issue #113.

As a tangential aside, the C# backing to *.resx is generated by an external tool (ie. [resgen.exe](https://msdn.microsoft.com/en-us/library/ccec7sz1(v=vs.110).aspx)) and not the C# compiler.

**Comment by twsouthwick** [comment]
@conniey this doesn't seem the same as #113 - there, TypeInfo is showing up due to it being derived and thus showing up as being on Type. This is an issue involving generated methods/types. These are usually annotated with some sort of attribute - maybe we could add a way to filter those out?

**Comment by twsouthwick** [comment]
An example: https://github.com/Microsoft/dotnet-apiport/blob/master/src/Microsoft.Fx.Portability/Resources/LocalizedStrings.Designer.cs

The type has `[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]` which we *may* be able to filter out - not sure how much work that would be in the metadata reader.

**Comment by conniey** [comment]
Ahh, I see what you're saying now.. Hmm that may be a little work due to how we calculate the docIds in MetadataReader.

**Comment by conniey** [comment]
Look at this feature when IOperation is available.

**Comment by Lxiamail** [comment]
Rerun the resgen tool supporting .NET standard should fix the issue.
