### ISSUE TITLE
offline mode not working

### ISSUE THREAD

**Issue by raffaeler** [Microsoft/dotnet-apiport#276]
Hi,
I am trying to generate a report using the offline mode.
The steps were the following:
- cloned the repo locally
- built with VS2015 ... success
- *clean* in order to delete the binaries
- build using the command line (build.cmd)
- run the ApiPort using the command line from the following folder:
   dotnet-apiport\bin\Release\ApiPort.Offline 

**This is the command line I used:**
`ApiPort analyze -f c:\temp\test.dll -t ".NET CORE, Version=5.0" -o test.html -r html`
**The output of the tool is the following:**
```
Detecting assembly references                     [Done]
Sending data to service                           [Failed]

There was an unknown error code from the service: 'ProxyAuthenticationRequired'.
  Please make sure you have the most up-to-date version.
```

Why is the tool still trying to send data to the service?
How can I use it totally offline?

Thanks

**Comment by raffaeler** [comment]
Still broken.
This is the log after clean, rebuild and run.


Microsoft (R) API Portability Analyzer v1.2.1.alpha.00000
Copyright (C) Microsoft Corporation. All rights reserved.

This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).

To learn more about how this tool works, including the data we are collecting, 
go here - http://go.microsoft.com/fwlink/?LinkId=397652

Loading catalog                                    [Done]
ApiPort Error: 0 : Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "ApiPort.ConsoleApiPort", name = "(none)".
Exception occurred while: Calling constructor Microsoft.Fx.Portability.OfflineApiCatalogLookup(Microsoft.Fx.Portability.IProgressReporter progressReporter).
Exception is: NullReferenceException - Object reference not set to an instance of an object.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving ApiPort.ConsoleApiPort,(none)
  Resolving parameter "apiPortClient" of constructor ApiPort.ConsoleApiPort(Microsoft.Fx.Portability.ApiPortClient apiPortClient, Microsoft.Fx.Portability.ITargetMapper targetMapper, Microsoft.Fx.Portability.IApiPortOptions options, ApiPort.DocIdSearchRepl repl)
    Resolving Microsoft.Fx.Portability.ApiPortClient,(none)
    Resolving parameter "apiPortService" of constructor Microsoft.Fx.Portability.ApiPortClient(Microsoft.Fx.Portability.IApiPortService apiPortService, Microsoft.Fx.Portability.IProgressReporter progressReport, Microsoft.Fx.Portability.ITargetMapper targetMapper, Microsoft.Fx.Portability.Analyzer.IDependencyFinder dependencyFinder, Microsoft.Fx.Portability.Reporting.IReportGenerator reportGenerator, System.Collections.Generic.IEnumerable`1[[Microsoft.Fx.Portability.ObjectModel.IgnoreAssemblyInfo, Microsoft.Fx.Portability, Version=1.4.0.0, Culture=neutral, PublicKeyToken=4a286c3e845c3e69]] assembliesToIgnore, Microsoft.Fx.Portability.Reporting.IFileWriter writer)
      Resolving Microsoft.Fx.Portability.OfflineApiPortService,(none) (mapped from Microsoft.Fx.Portability.IApiPortService, (none))
      Resolving parameter "lookup" of constructor Microsoft.Fx.Portability.OfflineApiPortService(Microsoft.Fx.Portability.ObjectModel.IApiCatalogLookup lookup, Microsoft.Fx.Portability.Analyzer.IRequestAnalyzer requestAnalyzer, Microsoft.Fx.Portability.ITargetMapper mapper, System.Collections.Generic.ICollection`1[[Microsoft.Fx.Portability.Reporting.IReportWriter, Microsoft.Fx.Portability, Version=1.4.0.0, Culture=neutral, PublicKeyToken=4a286c3e845c3e69]] reportWriters, Microsoft.Fx.Portability.ITargetNameParser targetNameParser, Microsoft.Fx.Portability.ObjectModel.IApiRecommendations apiRecommendations)
        Resolving Microsoft.Fx.Portability.OfflineApiCatalogLookup,(none) (mapped from Microsoft.Fx.Portability.ObjectModel.IApiCatalogLookup, (none))
        Calling constructor Microsoft.Fx.Portability.OfflineApiCatalogLookup(Microsoft.Fx.Portability.IProgressReporter progressReporter)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Fx.Portability.ObjectModel.CloudApiCatalogLookup..ctor(DotNetCatalog catalog) in C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability\ObjectModel\CloudApiCatalogLookup.cs:line 31
   at lambda_method(Closure , IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at lambda_method(Closure , IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at lambda_method(Closure , IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuilderContext.NewBuildUp(NamedTypeBuildKey newBuildKey)
   at lambda_method(Closure , IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   --- End of inner exception stack trace ---
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at ApiPort.Program.Main(String[] args) in C:\Samples\dotnet-apiport\src\ApiPort\Program.cs:line 18

There was an unexpected error.  Please try again or contact NETAPIPort@Microsoft.com for help.

**Comment by conniey** [comment]
@raffaeler  : I am unable to reproduce this issue. What command did you run to get that error?

**Comment by twsouthwick** [comment]
I've seen reports of this before, but have never gotten a good repro. @raffaeler the command @conniey asked for, as well as the environment you're using would be very helpful.

**Comment by raffaeler** [comment]
I run the tool inside a corporate network with an authenticated proxy.
Before the @conniey changes the tool run in "online" mode and I could see an authentication error in the command line.
After @conniey fix, the error became the exception I posted.

The command line is very basic. 
ApiPort analyze -f c:\temp\test.dll -t ".NET CORE, Version=5.0" -o test.html -r html
or
ApiPort analyze -f c:\temp\test.dll -t ".NET CORE, Version=5.0" -o test.json -r json

This is the output of the build.cmd on the VS2015 developer prompt (as admin, just to be sure it does not depend on my user privileges).

As you can see there are build errors related to DotNetCore but the other binaries were created.


```
C:\Samples\dotnet-apiport>build
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
)\MSBuild\14.0\bin'.
Feeds used:
**  (REMOVED, there are many)**

Restoring packages for C:\Samples\dotnet-apiport\src\ApiPort\ApiPort.project.jso
n...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win-anycpu).
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file ApiPort.nuget.targets.
Generating MSBuild file ApiPort.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\tests\Microsoft.Fx.Portability.
MetadataReader.Tests\project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.MetadataReader.Tests.nuget.targ
ets.
Generating MSBuild file Microsoft.Fx.Portability.MetadataReader.Tests.nuget.prop
s.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability.Re
ports.Html\Microsoft.Fx.Portability.Reports.Html.project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.Reports.Html.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.Reports.Html.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability.Of
fline\Microsoft.Fx.Portability.Offline.project.json...
All packages are compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with UAP,Version=v10.0.
All packages are compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
Generating MSBuild file Microsoft.Fx.Portability.Offline.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.Offline.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability\Mi
crosoft.Fx.Portability.project.json...
All packages are compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with UAP,Version=v10.0.
All packages are compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
Generating MSBuild file Microsoft.Fx.Portability.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability.Me
tadataReader\Microsoft.Fx.Portability.MetadataReader.project.json...
All packages are compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
Microsoft.NETCore.Portable.Compatibility 1.0.1-beta-23516 provides a compile-tim
e reference assembly for mscorlib on DNXCore,Version=v5.0, but there is no run-t
ime assembly compatible with win7-x86.
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86).
Microsoft.NETCore.Portable.Compatibility 1.0.1-beta-23516 provides a compile-tim
e reference assembly for mscorlib on DNXCore,Version=v5.0, but there is no run-t
ime assembly compatible with win7-x64.
Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
Generating MSBuild file Microsoft.Fx.Portability.MetadataReader.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.MetadataReader.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\tests\Microsoft.Fx.Portability.
Tests\project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.Tests.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.Tests.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability.Re
ports.Json\Microsoft.Fx.Portability.Reports.Json.project.json...
All packages are compatible with .NETPlatform,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6.
All packages are compatible with UAP,Version=v10.0.
All packages are compatible with DNXCore,Version=v5.0.
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
All packages are compatible with DNXCore,Version=v5.0 (win7-x86).
All packages are compatible with DNXCore,Version=v5.0 (win7-x64).
Generating MSBuild file Microsoft.Fx.Portability.Reports.Json.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.Reports.Json.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability\Mi
crosoft.Fx.Portability.NET45.project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.NET45.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.NET45.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability.Me
tadataReader\Microsoft.Fx.Portability.MetadataReader.NET45.project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.MetadataReader.NET45.nuget.targ
ets.
Generating MSBuild file Microsoft.Fx.Portability.MetadataReader.NET45.nuget.prop
s.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability.Of
fline\Microsoft.Fx.Portability.Offline.NET45.project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.Offline.NET45.nuget.targets.
Generating MSBuild file Microsoft.Fx.Portability.Offline.NET45.nuget.props.
Restoring packages for C:\Samples\dotnet-apiport\src\Microsoft.Fx.Portability.Re
ports.Json\Microsoft.Fx.Portability.Reports.Json.NET45.project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.Reports.Json.NET45.nuget.target
s.
Generating MSBuild file Microsoft.Fx.Portability.Reports.Json.NET45.nuget.props.

Restoring packages for C:\Samples\dotnet-apiport\tests\Microsoft.Fx.Portability.
Offline.Tests\project.json...
All packages are compatible with .NETFramework,Version=v4.5.
All packages are compatible with .NETFramework,Version=v4.5 (win).
Generating MSBuild file Microsoft.Fx.Portability.Offline.Tests.nuget.props.
Attempt to download to C:\Samples\dotnet-apiport\build\..\.data\catalog.bin
**Failed to download 'https://portabilitystorage.blob.core.windows.net/catalog/cat
alog.bin?sr=c&sv=2015-02-21&si=ReadCatalog&sig=8tOHoX2ZvcSFLol0GI6lxmydNPJbnJdHN
LKr06aD7t4%3D'
  Microsoft.Fx.Portability -> C:\Samples\dotnet-apiport\bin\Release\Microsoft.F
  x.Portability\dotnet\Microsoft.Fx.Portability.dll
  Microsoft.Fx.Portability.NET45 -> C:\Samples\dotnet-apiport\bin\Release\Micro
  soft.Fx.Portability\net45\Microsoft.Fx.Portability.dll
  Microsoft.Fx.Portability.Reports.Json.NET45 -> C:\Samples\dotnet-apiport\bin\
  Release\Microsoft.Fx.Portability.Reports.Json\net45\Microsoft.Fx.Portability.
  Reports.Json.dll
  Microsoft.Fx.Portability.MetadataReader.NET45 -> C:\Samples\dotnet-apiport\bi
  n\Release\Microsoft.Fx.Portability.MetadataReader\net45\Microsoft.Fx.Portabil
  ity.MetadataReader.dll
  Microsoft.Fx.Portability.Offline.NET45 -> C:\Samples\dotnet-apiport\bin\Relea
  se\Microsoft.Fx.Portability.Offline\net45\Microsoft.Fx.Portability.Offline.dl
  l
  ApiPort -> C:\Samples\dotnet-apiport\bin\Release\ApiPort\net45\ApiPort.exe
  Microsoft.Fx.Portability.Tests -> C:\Samples\dotnet-apiport\tests\Microsoft.F
  x.Portability.Tests\bin\Release\Microsoft.Fx.Portability.Tests.dll
CSC : warning AD0001: Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.FixAnal
yzers.CSharpFixerWithFixAllAnalyzer' threw an exception of type 'System.TypeIni
tializationException' with message 'The type initializer for 'Microsoft.CodeAna
lysis.Analyzers.FixAnalyzers.FixerWithFixAllAnalyzer`1' threw an exception.'. [
C:\Samples\dotnet-apiport\tests\Microsoft.Fx.Portability.MetadataReader.Tests\M
icrosoft.Fx.Portability.MetadataReader.Tests.csproj]
  Microsoft.Fx.Portability.MetadataReader.Tests -> C:\Samples\dotnet-apiport\te
  sts\Microsoft.Fx.Portability.MetadataReader.Tests\bin\Release\Microsoft.Fx.Po
  rtability.MetadataReader.Tests.dll
  Microsoft.Fx.Portability.Offline -> C:\Samples\dotnet-apiport\bin\Release\Mic
  rosoft.Fx.Portability.Offline\dotnet\Microsoft.Fx.Portability.Offline.dll
  Microsoft.Fx.Portability.Reports.Html -> C:\Samples\dotnet-apiport\bin\Releas
  e\Microsoft.Fx.Portability.Reports.Html\net45\Microsoft.Fx.Portability.Report
  s.Html.dll
  Microsoft.Fx.Portability.Reports.Json -> C:\Samples\dotnet-apiport\bin\Releas
  e\Microsoft.Fx.Portability.Reports.Json\dotnet\Microsoft.Fx.Portability.Repor
  ts.Json.dll
  SearchFxApi -> C:\Samples\dotnet-apiport\samples\SearchFxApi\bin\Release\Sear
  chFxApi.exe
  Microsoft.Fx.Portability.MetadataReader -> C:\Samples\dotnet-apiport\bin\Rele
  ase\Microsoft.Fx.Portability.MetadataReader\dotnet\Microsoft.Fx.Portability.M
  etadataReader.dll
  Microsoft.Fx.Portability.Offline.Tests -> C:\Samples\dotnet-apiport\tests\Mic
  rosoft.Fx.Portability.Offline.Tests\bin\Release\Microsoft.Fx.Portability.Offl
  ine.Tests.dll
**
Path    : C:\Samples\dotnet-apiport\bin\Release\Microsoft.Fx.Portability.Metada
          taReader\Microsoft.Fx.Portability.MetadataReader.1.1.1-alpha-00000.nu
          pkg
Pushed  : False
Nuspec  : Microsoft.Fx.Portability.MetadataReader.nuspec
Package : Microsoft.Fx.Portability.MetadataReader.1.1.1-alpha-00000.nupkg


Path    : C:\Samples\dotnet-apiport\bin\Release\Microsoft.Fx.Portability\Micros
          oft.Fx.Portability.1.4.0-alpha-00000.nupkg
Pushed  : False
Nuspec  : Microsoft.Fx.Portability.nuspec
Package : Microsoft.Fx.Portability.1.4.0-alpha-00000.nupkg

Path    : C:\Samples\dotnet-apiport\bin\Release\Microsoft.Fx.Portability.Offlin
          e\Microsoft.Fx.Portability.Offline.1.1.0-alpha-00000.nupkg
Pushed  : False
Nuspec  : Microsoft.Fx.Portability.Offline.nuspec
Package : Microsoft.Fx.Portability.Offline.1.1.0-alpha-00000.nupkg

Path    : C:\Samples\dotnet-apiport\bin\Release\Microsoft.Fx.Portability.Report
          s.Html\Microsoft.Fx.Portability.Reports.Html.2.0.0-alpha-00000.nupkg
Pushed  : False
Nuspec  : Microsoft.Fx.Portability.Reports.Html.nuspec
Package : Microsoft.Fx.Portability.Reports.Html.2.0.0-alpha-00000.nupkg

Path    : C:\Samples\dotnet-apiport\bin\Release\Microsoft.Fx.Portability.Report
          s.Json\Microsoft.Fx.Portability.Reports.Json.1.0.1-alpha-00000.nupkg
Pushed  : False
Nuspec  : Microsoft.Fx.Portability.Reports.Json.nuspec
Package : Microsoft.Fx.Portability.Reports.Json.1.0.1-alpha-00000.nupkg

C:\Samples\dotnet-apiport>

```

Finally here is the content of the apiport.offline folder:

```
26-Mar-16  13:17    <DIR>          .
26-Mar-16  13:17    <DIR>          ..
26-Mar-16  13:17            58,880 ApiPort.exe
22-Mar-16  10:53             1,068 ApiPort.exe.config
26-Mar-16  13:17           124,416 ApiPort.pdb
26-Mar-16  13:15            22,688 ApiPort.vshost.exe
22-Mar-16  10:53             1,068 ApiPort.vshost.exe.config
22-Mar-16  11:15           151,552 CommonMark.dll
26-Mar-16  13:17    <DIR>          LicenseTerms
22-Mar-16  11:15            13,816 Microsoft.Framework.Configuration.Abstraction
s.dll
22-Mar-16  11:15            19,960 Microsoft.Framework.Configuration.Binder.dll
22-Mar-16  11:15            18,424 Microsoft.Framework.Configuration.CommandLine
.dll
22-Mar-16  11:15            23,032 Microsoft.Framework.Configuration.dll
22-Mar-16  11:15            27,128 Microsoft.Framework.DependencyInjection.Abstr
actions.dll
22-Mar-16  11:15            21,496 Microsoft.Framework.OptionsModel.dll
26-Mar-16  13:17           154,112 Microsoft.Fx.Portability.dll
26-Mar-16  13:17            34,816 Microsoft.Fx.Portability.MetadataReader.dll
26-Mar-16  13:17            77,312 Microsoft.Fx.Portability.MetadataReader.pdb
26-Mar-16  13:17           214,528 Microsoft.Fx.Portability.Offline.dll
26-Mar-16  13:17            30,208 Microsoft.Fx.Portability.Offline.pdb
26-Mar-16  13:17           382,464 Microsoft.Fx.Portability.pdb
26-Mar-16  13:17            53,760 Microsoft.Fx.Portability.Reports.Html.dll
22-Mar-16  10:53             1,986 Microsoft.Fx.Portability.Reports.Html.dll.con
fig
26-Mar-16  13:17            38,400 Microsoft.Fx.Portability.Reports.Html.pdb
26-Mar-16  13:17             5,632 Microsoft.Fx.Portability.Reports.Json.dll
26-Mar-16  13:17            11,776 Microsoft.Fx.Portability.Reports.Json.pdb
22-Mar-16  11:15            86,176 Microsoft.Practices.Unity.Configuration.dll
22-Mar-16  11:15           132,256 Microsoft.Practices.Unity.dll
22-Mar-16  11:15            28,320 Microsoft.Practices.Unity.RegistrationByConve
ntion.dll
22-Mar-16  10:59           513,536 Newtonsoft.Json.dll
22-Mar-16  11:15           282,112 RazorEngine.dll
22-Mar-16  11:15           198,392 System.Collections.Immutable.dll
22-Mar-16  11:00           286,952 System.Reflection.Metadata.dll
22-Mar-16  11:15           271,056 System.Web.Razor.dll
22-Mar-16  10:53             2,792 unity.config

```

Hope this helps

**Comment by conniey** [comment]
I looked into it and the error occurs because we are unable to download `catalog.bin`, which is packaged into Microsoft.Fx.Portability.Offline.  So at runtime, it can't load the catalog (even though it says it was successful).

A couple of temporary workarounds are:

1. Execute: `mkdir .data` in the root of your repository
2. Manually download [catalog.bin]("https://portabilitystorage.blob.core.windows.net/catalog/catalog.bin?sr=c&sv=2015-02-21&si=ReadCatalog&sig=8tOHoX2ZvcSFLol0GI6lxmydNPJbnJdHNLKr06aD7t4%3D") into that folder
3. Run `build.cmd` again

__OR__

1. Edit [`.\build\Get-CatalogFile.ps1` atLine 24](https://github.com/Microsoft/dotnet-apiport/blob/master/build/Get-CatalogFile.ps1#L24)
2. Replace Line 24 with:
    1. If your proxy uses your default credentials: 
        `Invoke-WebRequest $url -OutFile $OutputPath -Proxy "Insert proxy address with port number" -ProxyUseDefaultCredentials`
    2. Otherwise:
        `Invoke-WebRequest $url -OutFile $OutputPath -Proxy "Insert proxy address with port number" -ProxyCredential "your username to login with"`
3. Run `build.cmd`

**Comment by twsouthwick** [comment]
Another option is to follow the steps explained here: http://stackoverflow.com/questions/15646079/invoke-webrequest-getsystemwebproxy.

Essentially, you can use `PSDefaultParameterValues` and set some default values in your profile.ps1. This, of course, assumes you're using powershell instead of cmd.

```powershell
if(Test-Connection myCorpProxy -Count 1 -Quiet)
{
    $global:PSDefaultParameterValues = @{
        'Invoke-RestMethod:Proxy'='http://myCorpProxy:8080'
        'Invoke-WebRequest:Proxy'='http://myCorpProxy:8080'
        '*:ProxyUseDefaultCredentials'=$true
    }
}
```

**Comment by raffaeler** [comment]
Thanks for this additional info.
The baseline problem is that the corporation do not want the machine to connect to the internet since it has "sensible" data (the sources).
The best workaround would be to have an option to download the required data from another machine and then being able to run the tool, totally offline, on the one who can access the source code.

**Comment by twsouthwick** [comment]
@raffaeler The workaround I gave is only for the build step since at this time we don't provide a pre-built version of the offline mode as a download. Once you have it built, then you may run it offline (in the sense that no network connectivity is required).
