### ISSUE TITLE
ApiPort reports TypeInfo.IsClass is not supported in .NET 4.5

### ISSUE THREAD

**Issue by danielturcanu** [Microsoft/dotnet-apiport#285]
Wrote some small test code
            TypeInfo info = IntrospectionExtensions.GetTypeInfo(GetType());
            IsClass = info.IsClass;

For this ApiPort reports that TypeInfo.IsClass is not supported in .NET 4.5, but supported in .NET Core.
I can run this code just fine in .NET 4.5 though.

**Comment by twsouthwick** [comment]
Thanks @danielturcanu. We know there are some issues around Type/TypeInfo (see #113) and the way we can analyze them via IL. This may be related, but I'll take a look.

**Comment by twsouthwick** [comment]
Yes, this is related. We think we have a workaround, but we'll track that in the original issue
