### ISSUE TITLE
CharSet.Auto is missing from NetCore

### ISSUE THREAD

**Issue by ghost** [Microsoft/dotnet-apiport#299]
https://msdn.microsoft.com/en-us/library/system.runtime.interopservices.charset.aspx

In netcore, `Auto` is not present in `CharSet` enum, we only have `Ansi`, `Unicode` and `None`.

**Comment by conniey** [comment]
@weshaggard, @terrajobst: Would you be able to shed light why CharSet.Auto is not part of .NET Core?

@jasonwilliams200OK : A good place to ask these questions is in the [corefx repository](https://github.com/dotnet/corefx/issues).

**Comment by weshaggard** [comment]
@yizhang82 might be able to talk to that.

**Comment by yizhang82** [comment]
@jasonwilliams200OK CharSet.Auto is UTF-16 across the board these days (no Win9x anymore), so there is no point including CharSet.Auto in .NET Core.

**Comment by twsouthwick** [comment]
@yizhang82 does that mean the recommendation is to switch all `CharSet.Auto` to `CharSet.Unicode` now?
