### ISSUE TITLE
No options for Target Platform

### ISSUE THREAD

**Issue by PirateJubber** [Microsoft/dotnet-apiport#301]
When I open up Tools>Options>.Net Portability Analyzer, I am faced with an empty gray box. It doesn't give me any options.

I have tried uninstalling and reinstalling.
I am on VS 2015 Pro Update 2.
Could it be related to my internet browsing being very restrictive?

**Comment by conniey** [comment]
Do your internet requests go through a proxy?  The platforms are populated through a call to our Portability service in Azure. You can check if the call is successful by:

1. Run Fiddler
2. Open VS 2015
3. Browse to the ".NET Portability Analyzer" tab
4. Check request is returning success
![image](https://cloud.githubusercontent.com/assets/10136526/16020702/0ff44962-3164-11e6-887a-bd8b95b006cd.png)

Related to #276.

**Comment by PirateJubber** [comment]
Yes it looks like it is successful

**Comment by conniey** [comment]
Can you try downloading the console application from [releases](https://github.com/Microsoft/dotnet-apiport/releases/tag/v1.2.1.alpha.00031) and executing: `ApiPort.exe listTargets`? Does it successfully display all the available targets?

**Comment by PirateJubber** [comment]
![capture](https://cloud.githubusercontent.com/assets/19915933/16240275/e68f097a-37a5-11e6-914a-0c3306623c42.PNG)

**Comment by PirateJubber** [comment]
I am on a corporate network, which looks like it uses a PAC file and we use Invincea. Is there any way to configure Visual Studio to allow this extension to contact your web service to get the targets?

**Comment by conniey** [comment]
I did some searching and some users have been able to get it working by adding a configuration to their `devenv.exe.config` like the one below. Admittedly, I have not been able to try this because we do not use a proxy. I'll verify this when I get an environment set up.

* [Proxy Authentication with Visual Studio](https://msdn.microsoft.com/en-us/library/dn771556.aspx)
* [Documentation](https://msdn.microsoft.com/en-us/library/dkwyc043(v=vs.110).aspx) for more proxy configuration attributes: 

```
<system.net>
    <settings>
        <ipv6 enabled="true"/>
    </settings>
    <defaultProxy useDefaultCredentials="true" enabled="true">
        <proxy bypassonlocal="true" proxyaddress="http://proxy-server:3128" />
    </defaultProxy>
</system.net>
```

It'd be great if you could let us know whether or not this works for you so we can document it.

**Comment by PirateJubber** [comment]
I have tried adding the code above but it still does not let me through.

**Comment by twsouthwick** [comment]
@PirateJubber Did you restart visual studio? The config is read at startup.

**Comment by PirateJubber** [comment]
I did restart visual studio, as well as tried uninstalling/reinstalling/reconfiguring to no avail. I have taken up the issue with my Corporate IT and will let them see what they can do as I'm 99% sure its just that I am not configuring something in the background right. I went ahead and got it working on an off network machine so I can use it in a round about way for now. 

I did have another question and I am not sure where exactly to ask it. When I am using the tool to analyze projects in VS 2015, I get the report every time, but not always detailed messages in the error list. In fact, I only get messages for about 1/5 of the files I analyze, even when the analysis comes back as a low percentage (like 65%). Do the messages only display for certain project types? I believe most of the projects I am analyzing are of similar types.

Thanks

**Comment by twsouthwick** [comment]
Ok - if you find something out from your IT that we could do differently to make this easier, please let us know.

@conniey  has been working on updating the VS integration, so she's probably better to answer your second question. It supports csproj, vbproj, and fsproj AFAIK; which project types are you using? Do you see any pattern of which ones are available and which ones are not?

**Comment by twsouthwick** [comment]
Please re-open if you learn anything that's a problem on our side.
