### ISSUE TITLE
[Question] Plans to update new VSIX

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/dotnet-apiport#302]
The VSIX on the VS Gallery was posted in 12/15.  Are there plans to add a newer version after Core v1 is RTMed?

**Comment by conniey** [comment]
I am currently working on updating and open-sourcing the VSIX.

**Comment by shaggygi** [comment]
@conniey thanks for reply and work :smile:

**Comment by ArturKarbone** [comment]
Any plans, predictions when the new version is going to be shipped ?

**Comment by conniey** [comment]
@ArturKarbone I plan on shipping a version sometime by the end of this week with a bug fix.  And hopefully within the next two sprints, get the VSIX in the public

**Comment by SychevIgor** [comment]
@conniey I hope vsix will be published soon. .net core released ~1.5month ago and some dev already porting their apps a library. this tools will be very useful for us.

**Comment by conniey** [comment]
@SychevIgor Hi.  You should already see the new targets in the existing VSIX. The extension gets those platforms and APIs from an Azure cloud service every time you use it. As a result, no real analysis is done in the VSIX; we propagate that information to Azure to perform analysis and send you back a result.

Tools > Options > .NET Portability Analyzer
![platform](https://cloud.githubusercontent.com/assets/10136526/18238225/af05fae2-72ef-11e6-8f58-8f114395ef89.png)

**Comment by jnm2** [comment]
@conniey I did not pick up on that! That's cool! Maybe there could be some way to notify users when significant updates are made so they know to run it again?

**Comment by twsouthwick** [comment]
@jnm2 Can you create an issue to track that as a feature request?

**Comment by conniey** [comment]
I've updated the VSIX here: https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a8a6-e56c7905292b

**Comment by shaggygi** [comment]
@conniey thank you

**Comment by twsouthwick** [comment]
Closing this now that the VSIX has been updated.
