### ISSUE TITLE
Do not understand report

### ISSUE THREAD

**Issue by ErikEJ** [Microsoft/dotnet-apiport#306]
Target type .NET Framework,Version=v4.6.1 
System.String[0:,0:,0:]   
0:,0:,0:].#ctor(System.Int32,System.Int32,System.Int32)   
0:,0:,0:].Get(System.Int32,System.Int32,System.Int32)   
0:,0:,0:].Set(System.Int32,System.Int32,System.Int32,System.String)   

- what does this mean?

**Comment by twsouthwick** [comment]
Do you have some sample code that generates this report? There are some known issues around multi-dimensional arrays that this may fall into.

**Comment by ErikEJ** [comment]
I could share the dll??

**Comment by twsouthwick** [comment]
That would be ideal so we can look at the types it's finding. My email is tasou at microsoft dot com

**Comment by twsouthwick** [comment]
I took a look at the assembly @ErikEJ is using and it is the same issue as #42. Thanks for reporting - we'll see if someone can look into it. I'm going to close this issue as the other issue is the root cause.
