### ISSUE TITLE
APIPort reporting issues with DateTimeOffset constructors, but they exist in corefx

### ISSUE THREAD

**Issue by EricZimmerman** [Microsoft/dotnet-apiport#309]
additionally, no constructors seem to work.

this is the code i have:

 var dtoffset = new DateTimeOffset(DateTime.Now,TimeSpan.Zero);

and i have tried several other variations. the corefx code is full of such references like this too:

var dateTimeOffset = new DateTimeOffset(new DateTime(2012, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc));

yet when i add this to my class and use apiport, i get things like this:

![image](https://cloud.githubusercontent.com/assets/4265254/16742195/9e403598-4774-11e6-8e7d-de5e038f2de4.png)

so is that supported or no?

finally, vs2015 compiles my code without issue. why would it do that if it wasnt supported?

**Comment by conniey** [comment]
@terrajobst Immo, is there an issue with the API catalog? I was looking and it looks like none of the DateTimeOffset ctors are supported in .NET Core 5.0.

**Comment by EricZimmerman** [comment]
APIPort also complained heavily about nullable types but no compile errors in VS

**Comment by conniey** [comment]
@EricZimmerman Can you give me an example so I can look into this?

**Comment by EricZimmerman** [comment]
An apiport output example or a code snippet?

**Comment by conniey** [comment]
A code snippet, please.

**Comment by EricZimmerman** [comment]
the code in the try/catch block is what is throwing the warnings in apiport. i have a bunch of other code related to nullable all over the place but this function exhibits it as well

```
 public static DateTimeOffset? ExtractDateTimeOffsetFromBytes(byte[] rawBytes)
        {
            DateTimeOffset? thedate = null;

            var somedate = BitConverter.ToUInt16(rawBytes, 0);

            var day = (somedate & 0x1f);
            var month = (somedate & 0x1e0) >> 5;
            var year = ((somedate & 0xfe00) >> 9) + 1980;

            var sometime = BitConverter.ToUInt16(rawBytes, 2);

            var someTimeBinary = Convert.ToString(sometime, 2).PadLeft(16, '0');

            var chunkt1 = someTimeBinary.Substring(0, 5);
            var chunkt2 = someTimeBinary.Substring(5, 6);
            var chunkt3 = someTimeBinary.Substring(11, 5);

            var hour = (int) Convert.ToUInt32(chunkt1, 2);
            var minute = (int) Convert.ToUInt32(chunkt2, 2);
            var seconds = (int) Convert.ToUInt32(chunkt3, 2)*2;

            try
            {
                var dt = DateTime.Now;
                //var dt = new DateTime(year, month, day, hour, minute, seconds, DateTimeKind.Utc);
               
                var d = new DateTimeOffset();
                var dateTimeOffset = new DateTimeOffset(year,month,day,hour,minute,seconds,0,TimeSpan.Zero);

//                var dtoffset = new DateTimeOffset(DateTime.Now,TimeSpan.Zero);
//
//                thedate = dtoffset;
            }
            catch (Exception)
            {
                
                    return null;
                
            }

            return thedate;
        }
```

**Comment by conniey** [comment]
I apologise for not circling back to this issue but it should have been resolved. I don't see it listed as unavailable anymore and the catalog surfaced by https://apisof.net/catalog/System.DateTimeOffset..ctor(DateTime,TimeSpan) have it.
