### ISSUE TITLE
System.Boolean.ToString() is supported but the tool says otherwise

### ISSUE THREAD

**Issue by petrroll** [Microsoft/dotnet-apiport#314]
Hi, the tool mistakenly identifies `System.Boolean.ToString() `as a missing API from most Target types (.NET Core 1.0, 1.1, Full Framework 4.6.2, .NET Standard v1.7, ...) while it's (obviously) present.

Repro:
1) Create a .NET 4.5.x and a .NET Core Console app projects.
2) Copy following code to both of them:
```
using System;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Boolean a = true;
            writeOut(a.ToString());
        }

        private static void writeOut(string s)
        {
            Console.WriteLine(s);
        }
    }
} 
```
3) Run analysis on the FullFramework one -> following problem will show up
![error_1](https://cloud.githubusercontent.com/assets/1764721/18028493/2bc30608-6c81-11e6-8fdc-d7b7478d8941.PNG)

4) Try to build the .NET Core one -> it will work fine :)

![works_1](https://cloud.githubusercontent.com/assets/1764721/18028516/7557af6c-6c81-11e6-9eef-f0544b816115.PNG)

**Comment by twsouthwick** [comment]
@petrroll This should be fixed as of today in a recent data update. Please let us know if it works or if you are still seeing the issue.

**Comment by twsouthwick** [comment]
Please re-open if you still see the issue.
