### ISSUE TITLE
Provide a notification when new targets become available in VS extension

### ISSUE THREAD

**Issue by jnm2** [microsoft/dotnet-apiport#331]
Since new versions are shipped on the server side (see #302) rather than via the extensions updater, you don't get notifications for it. It would be nice to know when this happens in case you might want to run the tool again.

(As requested.)

**Comment by twsouthwick** [comment]
Thanks, @jnm2. The catalog gets updated every night, so this may cause a lot of excess notifications. Are you looking for notification when a specific API gets added or when new targets are added?

**Comment by jnm2** [comment]
All that matters to me so far is when new targets are available.

**Comment by twsouthwick** [comment]
Ah, ok. That's a much more doable request :) I'll update the title to reflect that

**Comment by Lxiamail** [comment]
Feel free to reopen if you have additional suggestion.
