### ISSUE TITLE
.NET Core 1.1(App?)

### ISSUE THREAD

**Issue by assafk1** [Microsoft/dotnet-apiport#346]
Hi,
.Net Core 5.0 used to show up as ".Net Core 5.0" in the output of "listTargets". I installed the new .NET Core 1.0.1 - VS 2015 Tooling Preview 2  from https://www.microsoft.com/net/core#windows and what i see now is the following:

Retrieving targets                                [Done]

Available Targets:
- .NET Core App [Version: 1.1*; 1.0]
- .NET Framework [Version: 1.1; 2.0; 3.0; 3.5; 4.0; 4.5; 4.5.1; 4.5.2; 4.6; 4.6.1; 4.6.2*]
- .NET Standard [Version: 1.0; 1.1; 1.2; 1.3; 1.4; 1.5; 1.6; 2.0*]
- ASP.NET Core [Version: 1.0]
- Mono [Version: 2.0; 4.0; 4.5; 3.5]
- Silverlight [Version: 2.0; 3.0; 4.0; 5.0]
- Windows [Version: 8.0; 8.1; 10.0]
- Windows Phone [Version: 8.1]
- Windows Phone Silverlight [Version: 7.0; 7.1; 8.0; 8.1]
- Xamarin Android [Version: 1.0.0]
- Xamarin iOS [Version: 1.0.0.0]

Which one of these is referring to .NET Core 1.0.1? is it **- .NET Core App [Version: 1.1*; 1.0]** ?
I'm interested in porting a console application to .NET Core, not an ASP.NET application.

**Comment by Petermarcu** [comment]
Its .NET Core App 1.0. It was decided to treat it as a new product ans start it at 1.0 while previews were at 5.0.

**Comment by Petermarcu** [comment]
Note, that in 1.2 we are bringing in a ton more apis to support .net standard. If you see gaps, you can also run it against .NET Standard 2.0 and see if its there. If it is, we plan on implementing it in .NET Core App 1.2.

**Comment by assafk1** [comment]
Awesome thanks!
1.1 is not released yet is it? Looks like it was scheduled for fall 2016 according to the [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md). Can you share any timelines beyond what is written there?

**Comment by Petermarcu** [comment]
Yes, it will be before the end of the year if all goes as planned. There should be a preview available very soon. 1.1 doesnt have a ton of new apis and apiport will already be mostly correct because its done from an api perspective. 1.2 is the wave where tons of apis will be added.

**Comment by assafk1** [comment]
Cheers!
Thanks
