### ISSUE TITLE
Visual Studio Extension Error

### ISSUE THREAD

**Issue by modulexcite** [Microsoft/dotnet-apiport#355]
Hi,

Thank you for the extension.
The new version of the extension 1.3.0.114 downloaded from VSIX gallery is throwing an error "could not load file or assembly Autofac" and it seems like the packaged vsix is missing a few dependent libraries such as Autofac, etc.
I'm using Visual Studio 2015 Update 3, the older version v1.2 of this extension from the MSDN gallery seems to work fine and has the dependent assemblies packaged with it.
Please let me know if you need more information.

**Comment by conniey** [comment]
Thanks for letting us know. Surprised that we have folks Dogfooding that CI build already! I am working on fixing this issue. It was due to my PR #354 . :/

**Comment by modulexcite** [comment]
Guilty:)
Thought I'd get on the new features bandwagon for this extension before it bit me in the ass:)

___________________________
Thanks.




On Thu, Oct 13, 2016 at 11:52 AM -0400, "Connie Yau" <notifications@github.com> wrote:












Thanks for letting us know. Surprised that we have folks Dogfooding that CI build already! I am working on fixing this issue. It was due to my PR #354 . :/

**Comment by modulexcite** [comment]
Thanks for fixing it by the way:)

**Comment by twsouthwick** [comment]
@connie just saw this issue, but I think a PR I just submitted will fix this issue. By switching to project.json, the NuGet dependencies were not being included by default into the VSIX. I found a work-around for now.

**Comment by twsouthwick** [comment]
@modulexcite can you update to the latest version and give it a try?

**Comment by twsouthwick** [comment]
You'll need 1.3.0.115 or later

**Comment by modulexcite** [comment]
Has it been published to the VSIX gallery?

**Comment by modulexcite** [comment]
Never mind, see it on the gallery.

**Comment by modulexcite** [comment]
Now i get a different error upon running the analyzer, see below. I failed to mention earlier that I'm on a Windows 7 SP1 OS with VS 2015 Professional Update 3.
***
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

**Comment by conniey** [comment]
@modulexcite Weird. It may be because a few of our last builds had the incorrect digital signature. We fixed it in version 1.3.0.117 (the latest one on the vsixgallery.com). 

In the meantime, I'll spin up a Windows 7 VM and try to repro your issue.

**Comment by modulexcite** [comment]
Version 1.3.0.118 seems to be working, thank you guys.

**Comment by modulexcite** [comment]
I found another unrelated issue. 
Whenever I open the Visual Studio options, the extension is creating a "Portability Analysis" folder in the "My Documents" directory which is the default output directory that you can specify under options for the extension even though I asked it to use a different directory for the output.

**Comment by conniey** [comment]
Thanks! I've created an issue for that #359
