### ISSUE TITLE
netcoreapp version crashes

### ISSUE THREAD

**Issue by johnkors** [Microsoft/dotnet-apiport#379]
This version of apiport is not expecting a certian dotnet core version to be installed on my system, right? It should just work, as it's bundled with the dotnet core version it needs? Or am I missing something?

```
C:\code\core\dotnet-apiport\bin\Release\ApiPort\netcoreapp1.0\x64 (master)
λ ApiPort.exe

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.ConsolePal.OpenStandardOutput()
   at System.Console.<>c.<get_Out>b__25_0()
   at System.Console.EnsureInitialized[T](T& field, Func`1 initializer)
   at System.Console.get_Out()
   at System.Console.WriteLine(String format, Object arg0, Object arg1)
   at ApiPort.Program.Main(String[] args) in C:\code\core\dotnet-apiport\src\ApiPort\Program.cs:line 22
```

**Comment by johnkors** [comment]
For what it's worth, I've dotnet 1.1.0 installed outside that folder.

**Comment by Petermarcu** [comment]
Looks like it's depending on 1.0.X because it's a netcoreapp1.0 app. Try installing 1.0.X.

**Comment by johnkors** [comment]
Isn't this a self-contained app meaning it comes with all it's deps (also dotnet core 1.0.x)?

**Comment by conniey** [comment]
It may be because we are using msbuild to build the netcoreapp1.0 instead of the .NET CLI tools.

**Comment by scottaddie** [comment]
@conniey Does this mean that VS 2017 RC is required in order to compile the .NET Core project with MSBuild?

**Comment by johnkors** [comment]
It think all MSBuild does is pipe everything to `dotnet` anyhow.

**Comment by conniey** [comment]
If you pull the latest version of master and build it, executing: `dotnet .\ApiPort\netcoreapp1.0\ApiPort.dll` should work now.
