### ISSUE TITLE
APIPort missing Dependencies tab

### ISSUE THREAD

**Issue by rnagpal** [Microsoft/dotnet-apiport#380]
I remember in earlier versions of APIPort that there used to be a External Dependencies tab which used to tell any external dependencies that your project has, so that we can ensure that we reference their .NET Core versions when compiling our project. This doesn't seems to be present in the latest APIPort version.

**Comment by conniey** [comment]
Sorry for the slow response, are you referring to the "Unresolved Assemblies" tab? It's still in the report if you have any that the client could not resolve.

If this isn't the case, please reopen.
