### ISSUE TITLE
unity.config file being ignored

### ISSUE THREAD

**Issue by scottaddie** [Microsoft/dotnet-apiport#382]
I wanted to view the data being transmitted to the portability service, so I created a `unity.config` file as described [here](https://github.com/Microsoft/dotnet-apiport/blob/master/docs/Console/README.md#see-the-data-being-transmitted). I then ran my ApiPort command again, and expected to see a file produced which would provide the data transmission detail. No such file was produced.

I dug into this a bit deeper and found that Autofac has replaced Unity as the IoC container. The associated PR is #289. It looks like this may have broken the functionality. Is there a way to enable this feature with Autofac? If so, the config file should be renamed accordingly (e.g., `autofac.config`).

**Comment by conniey** [comment]
Thanks for letting us know! I'll try to look into it
