### ISSUE TITLE
newtonsoft.json.jsoncovert.deserializeobject is reported as not supported in .NET 4.6.2

### ISSUE THREAD

**Issue by pabloarista** [Microsoft/dotnet-apiport#384]
I get this message that DesearilizeObject is not supported on .net 4.6.2

"newtonsoft.json.jsoncovert.deserializeobject``1(System.string) not supported on .net framework, version=v4.6.2"

I just installed .net 4.6.2 and I have no errors compiling and running this method

**Comment by conniey** [comment]
Currently we provide information about assemblies that are part of the .NET Framework (ie. System.*, Microsoft.*).  We don't analyse 3rd party assemblies, yet.

**Comment by pabloarista** [comment]
Got it. It didn't seem right, but it makes sense why now

**Comment by kvshripad** [comment]
Thanks Pabloarista! This still seems to be reported as false positive though. Any hint when can we start relying on third party assemblies portability (at list most used ones)?

**Comment by conniey** [comment]
@kvshripad, We have this on our backlog to complete but there is no milestone for when this would be integrated. A page you can check out which may have what you are looking for is: https://icanhasdot.net/
