### ISSUE TITLE
Could not find file

### ISSUE THREAD

**Issue by ygoe** [Microsoft/dotnet-apiport#390]
Running this on an ASP.NET Core 1.0 project targeting .NET Framework 4.6, with the then-proposed directory layout. Here's the output:

```
Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Detecting assembly references                      [Done]
* Could not find file: 'D:\Projekte\MyProjectName\Code\artifacts\bin\MyWebAssemblyName\'
* No files were found to upload.

Finding source line information
	                                               [Failed]
```

**Comment by bernd5** [comment]
This error seem to occur when we use the new csproj file format, really bad.
I have my code in shared projects. If add a reference of it to a "classic" project it works fine, but with the new format it fails...

**Comment by ygoe** [comment]
My original report was for project.json, which was available at that time. But it doesn't seem this tool gets any maintenance. With the upcoming .NET Standard/Core 2.0, this probably isn't much needed anymore anyway.

**Comment by dkent600** [comment]
I'm getting the same error, the analysis is unable to find folders that do exist.  :-(

```
Detecting assembly references                      [Done]
* Could not find file: 'C:\Users\[me]\Documents\Projects\CommonUtilitiesCore\CommonUtilitiesCore\bin\Debug\netcoreapp1.1\'
* Could not find file: 'C:\Users\[me]\Documents\Projects\CommonUtilitiesCore\CommonUtilitiesCoreTest\bin\Debug\netcoreapp1.1\'
* No files were found to upload.


Finding source line information
                                                       [Failed]
                                                       [Failed]
```

**Comment by conniey** [comment]
Hi,

Thanks for the issue feedback. It was because we were looking for `<OutputFileName>` in our ProjectAnalyzer for the binaries output from VS projects. I have a PR open for it #430 but am waiting to merge it in because the solution only works on VS2017 right now.  If you want, you can pull from that branch and build it.

**Comment by dkent600** [comment]
cool, thanks for the update!
