### ISSUE TITLE
Unable to contact service. Try again later

### ISSUE THREAD

**Issue by ashutoshbhaskar** [Microsoft/dotnet-apiport#391]
Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Using default target platforms.
To select platforms, visit Tools->Options->.NET Portability Analyzer.
Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

**Comment by conniey** [comment]
I checked this and it works. There was a service degradation around the time you submitted this issue.  Can you try again?
