### ISSUE TITLE
Clarify that breaking changes addressed in servicing may not be reported

### ISSUE THREAD

**Issue by mjrousos** [microsoft/dotnet-apiport#393]
When using ApiPort to scan for potential breaking changes, there are a set of compatibility issues that were initially present in some release and were later addressed via a hotfix. Not all such issues are included in ApiPort's markdown files at the moment (since customers should typically be installing servicing updates). 

For completeness, we should add a comment in ApiPort reports (or output) when running in -b mode making note of this (that compatibility issues fixed in servicing may not be included).

/cc: @HollyAM

**Comment by Lxiamail** [comment]
Need to add comment in the result to communicate the report may not include all the issues.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
