### ISSUE TITLE
Feature: Support for Visual Studio for Mac

### ISSUE THREAD

**Issue by drocsid** [microsoft/dotnet-apiport#404]
Visual Studio for Mac is in preview. I am going to try running VS2015 in VirtualBOX for the time being, but would be easier if this supports Visual Studio for Mac.

**Comment by conniey** [comment]
The extensibility model for Mac is different than VS.  We could take a look at hosting at the tools in it but this may be a big task. We would be willing to take PRs for this but we won't be able to take a look at this anytime soon.

**Comment by Lxiamail** [comment]
This is not on the roadmap.
