### ISSUE TITLE
EmbeddedResources error on load

### ISSUE THREAD

**Issue by msollicito** [Microsoft/dotnet-apiport#407]
I get these errors when loading up the solution

![image](https://cloud.githubusercontent.com/assets/187311/24520661/3dd9adae-1557-11e7-94bb-1f1aa52565f8.png)

**Comment by conniey** [comment]
@msollicito Thanks for mentioning this! These are some weird false errors we get in VS2015 when building the solution. If you check the "Output" window, it should say that there were no failures.

These errors should disappear when we migrate to VS2017.

**Comment by conniey** [comment]
fixed with #411.
