### ISSUE TITLE
Feature Request: include major unsupported components in report summary

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/dotnet-apiport#416]
It would be nice to get a general idea about the major components that block the porting.  There could be a mapping from namespaces to components, e.g.,

System.AppDomain => App Domain
System.Windows.Forms => Win Forms
System.Windows.*** => WPF
System.Runtime.Remoting => Remoting/RPC

and `major` can be defined as greater than some chosen percentage.

**Comment by conniey** [comment]
This would be helpful.
* We would have to surface the Components list
* We can use the same infrastructure as recommended changes to identify which component a NS belongs in.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
