### ISSUE TITLE
ApiPort offline is broken

### ISSUE THREAD

**Issue by mjsabby** [Microsoft/dotnet-apiport#421]
I recently built a new copy of this repo and now ApiPort.Offline\ApiPort.exe is no longer getting built by the default build command.

There seem to be some dlls in that folder though, so I'm not sure if some other option is needed to get a full build of the offline version of the tool.

**Comment by conniey** [comment]
@mjsabby . Hi, can you try pulling again and building the solution?  It should generate a working ApiPort.Offline now.
