### ISSUE TITLE
Fix PR checks for Compatibility Issues and Recommended Changes

### ISSUE THREAD

**Issue by conniey** [microsoft/dotnet-apiport#425]
The webhooks for checking PR statuses hang forever.

![image](https://cloud.githubusercontent.com/assets/10136526/25760043/da93cb04-3189-11e7-9da5-bd243fc7b678.png)

**Comment by conniey** [comment]
Look at using Azure Service Functions to do this.

**Comment by Lxiamail** [comment]
Low priority. Closing.
