### ISSUE TITLE
Iterator block for IEnumerable<T1<T2,T3>> generates incorrect docid

### ISSUE THREAD

**Issue by twsouthwick** [Microsoft/dotnet-apiport#43]
Use the following as the input assembly:

	using System;
	using System.Collections.Generic;

	namespace Microsoft.Fx.Portability.MetadataReader.Tests
	{
		class CallOtherClass
		{
			static void Main(string[] args)
			{
				OtherClass.GetValues<int>();
			}
		}

		public class OtherClass
		{
			internal static IEnumerable<Tuple<T, int>> GetValues<T>()
			{
				yield break;
			}
		}
	}

The docid generated for GetValues<T> is incorrect - there is a `@` where there should be a `#`.
	
**Expected:** ``M:Microsoft.Fx.Portability.MetadataReader.Tests.OtherClass.<GetValues>d__0`1.System#Collections#Generic#IEnumerable{System#Tuple{T@System#Int32}}#GetEnumerator``
**Actual:** ``M:Microsoft.Fx.Portability.MetadataReader.Tests.OtherClass.<GetValues>d__0`1.System#Collections#Generic#IEnumerable{System#Tuple{T,System#Int32}}#GetEnumerator``

The generics may be a red herring, but that's the only way I can get it to compile in a way that it is detected by the dependency finder.  There are probably compiler optimizations in other cases.

**Comment by AlexGhiondea** [comment]
Do you mean that there is a ```@``` where a ```,``` is expected?

Actual: ```{T@System#Int32}``` 
Expected: ```{T,System#Int32}```

**Comment by twsouthwick** [comment]
Yes, although I may have the expected/backward mixed up it seems (something seems off in my description).  When you get the time to take a look at it, can you post a clarification?
