### ISSUE TITLE
Provide sources and non windows instructions for building ApiPort.Core

### ISSUE THREAD

**Issue by tioduke** [Microsoft/dotnet-apiport#431]
I was trying to build ApiPort.Core from sources on Linux x64 and I could not find the ApiPort.Core project.

It would also be nice to have some sort of instructions that don't require the use of powershell.

Thank you in advance.

**Comment by conniey** [comment]
@tioduke Hi, I opened a PR that hopefully addresses your issues. Let me know if you have any more issues.

Cheers,
Connie

**Comment by tioduke** [comment]
Thank you
