### ISSUE TITLE
500 Internal server error when trying to run portability analysis

### ISSUE THREAD

**Issue by karanjitsingh** [Microsoft/dotnet-apiport#434]
Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

**Comment by aagarwal10** [comment]
I am also receiving this exact same error today with latest version. Please help

**Comment by karanjitsingh** [comment]
Meanwhile, I wrote a small [script](https://gist.github.com/karanjitsingh/6de9e6dc4b0ae38e7542f789f07ba27f) to make do

@aagarwal10, see if this helps you

**Comment by conniey** [comment]
Hi,
Would you be able to provide a repro for your 500 error? Also, does it repro when you use the ApiPort console tool?

I'm trying to add better logging to our service side, so I can understand the errors better.

Thanks!
Connie

**Comment by aagarwal10** [comment]
I get this error when using analyzer using Visual Studio 2015 with latest updates;

Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Detecting assembly references [Done]
Analyzing compatibility [Failed]

There was an unknown error code from the service: 'InternalServerError'. Please make sure you have the most up-to-date version.

**Comment by conniey** [comment]
@aagarwal10 Would you be able to share the VS project it is failing on or a repro?

**Comment by aagarwal10** [comment]
the project it is failing on is a Proprietary Enterprise ASP.NET Project and not open source. However, it is a 4.6.1 Web Form application. We are using VS 2015 with latest updates

**Comment by conniey** [comment]
Thanks for letting me know. I was able to figure out what is wrong.  I'll try to get a fix within the hour.

**Comment by baumatron** [comment]
Also seeing this issue in VS 2017 Community, .NET Portability Analyzer 1.4.0.175. Looking forward to the fix!

**Comment by conniey** [comment]
A workaround for now, would be to go to `Analyze > Portability Analyzer Settings` in Visual Studio and select `Excel` as your report format instead of HTML.

**Comment by aagarwal10** [comment]
@conniey - workaround suggested by you worked for me. Any idea when we can have HTML Report Generation fixed?

**Comment by conniey** [comment]
@aagarwal10 I've updated the service just now. It HTML report generation should work.

**Comment by aagarwal10** [comment]
@conniey - HTML report generation now works, Thanks for the help

**Comment by conniey** [comment]
I'll close this but if anything comes up, feel free to open another issue. :)

**Comment by DanielCaspers** [comment]
Hey @conniey, I am seeing this same issue. Would it be best for me to open a new ticket? I am able to successfully work around it when I don't use HTML report generation. 

I don't want to go through making a sample, but I would welcome cloning my repository where I am experiencing the issue if it would help.

VS Community 2017
.NET Portability Analyzer 1.4.0.199
Windows 10 x64

**Comment by conniey** [comment]
@DanielCaspers Yeah, it would be awesome if you could point me to your repository so I can try to repro it. Did it work before? Just to make sure, when you use the VSIX extension, you cannot generate the HTML report but the Excel report works for yu.

**Comment by DanielCaspers** [comment]
@conniey It's at DanielCaspers/DigitalInspection.

I had no prior experience with the portability analyzer before tonight, actually. Downloaded the VSIX from Nuget Package Manager, and tried generating both an Excel and HTML in the same pass, but it failed with HTML checked.
