### ISSUE TITLE
Apis that are now supported

### ISSUE THREAD

**Issue by mikes-gh** [microsoft/dotnet-apiport#445]
I believe the following are now supported (and probably others) in netstandard2.0

See https://github.com/dotnet/corefx/issues/12887

However the tool says Not Supported in my project for the following.

M:System.Data.SqlClient.SqlBulkCopy.WriteToServer(System.Data.DataTable)
M:System.Data.SqlClient.SqlDataAdapter.#ctor(System.String,System.Data.SqlClient.SqlConnection)
T:System.Data.SqlClient.SqlDataAdapter

**Comment by conniey** [comment]
@terrajobst Immo, these are listed as under netcoreapp in ApiCatalog, but the [latest System.Data.Sql NuGet package](https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Data.SqlClient/4.5.0-preview2-25319-04) and that issue suggest that it should be in .NET Standard 2.0.  Is this an error in the catalog?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
