### ISSUE TITLE
Vsix installation failed with error: The extenstion manifest is invalid

### ISSUE THREAD

**Issue by GKotfis** [Microsoft/dotnet-apiport#447]
Version: NET Portability Analyzer v1.4.0.186.vsix

![image](https://user-images.githubusercontent.com/7391978/27626807-bf0d274c-5be9-11e7-9592-80144c12acae.png)

Extenstion was downloaded from Microsoft Marketplace [https://marketplace.visualstudio.com/items?itemNa
me=ConnieYau.NETPortabilityAnalyzer](url)

**Comment by conniey** [comment]
I just downloaded and installed the extension from the marketplace and did not get the same error.  What versions of Visual Studio do you have installed on your machine?

Cheers,
Connie

**Comment by GKotfis** [comment]
Two version:
VS2015 Professional 14.0.25431.01 Update 3
VS2017 Community 15.0.0+26228,9

Regards Grzegorz

**Comment by conniey** [comment]
I created a machine with both versions of Visual Studio but was unable to reproduce the issue and it installed correctly.  I found something similar on StackOverflow.  Can you try this solution? https://stackoverflow.com/a/33501473/4220757

Cheers,
Connie

**Comment by GKotfis** [comment]
Problem was with wrong default app for vsix files - I have "Visual studio selector". After changing to Microsoft VSIX Installer everything works. Thank you.
