### ISSUE TITLE
Add an alias for the current release on the Releases page

### ISSUE THREAD

**Issue by rogancarr** [Microsoft/dotnet-apiport#449]
The current [releases page](https://github.com/Microsoft/dotnet-apiport/releases) has a list of all the available builds. However, there is no alias to the "current" version. This makes it difficult to script installs because someone has to manually check the releases and update the script.

My use case: I am writing a script for [Apache REEF](reef.apache.org) to measure the number of CoreCLR issues in the codebase as part of the build process. I automate the install of DotNet ApiPort and use it to scan all of our DLLs and EXEs. I currently have the ApiPort release URL pointing to a specific version, but I would prefer that it always point to the latest release.

**Comment by rogancarr** [comment]
Here is the CLR compatibility script we use in the build of Apache REEF for anyone who wants to do something similar: https://github.com/apache/reef/blob/master/bin/AnalyzeClrCompatibility.ps1

**Comment by conniey** [comment]
Hi,
The latest release you can access by going to https://github.com/Microsoft/dotnet-apiport/releases/latest now.

Thanks!
Connie
