### ISSUE TITLE
Feature request: API Port should scan installed nuget packages

### ISSUE THREAD

**Issue by aszego** [microsoft/dotnet-apiport#450]
It'd be nice if API Port could include in a report what nugget packages satisfy portability, eventually with an update if available.

e.g. I want to check portability to .NET Standard 2.0, so it'd scan installed nuget packages and check if all of them support .NET Standard 2.0.

Thanks!

**Comment by conniey** [comment]
Thanks for suggesting this feature! It would definitely be helpful to end users.

**Comment by martinstenhoff** [comment]
Is this now supposed to be working? Scott Hunter's .NET Conf 2017 Keynote demo (7:30) suggests it is as he installed a nuget package not built for .NET Standard 2.0 and then ran the portability analyser to verify that the project was compliant with .Net Standard 2.0.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
