### ISSUE TITLE
Sending requests to service not using gzip/deflate encoding results in 500

### ISSUE THREAD

**Issue by conniey** [microsoft/dotnet-apiport#451]
If you write your own HttpClient to send requests to our service and it does not use gzip, it will throw an exception and you'll get a 500 response back.

**Expected**
Maybe a new exception being thrown back like `InvalidHttpClientEncoding` which derives from PortabilityException.

**Actual**
The user gets a 500 for unknown server error.

Message: `Unknown encoding type: <encoding>. Only supports 'gzip' and 'deflate'.`

```
System.InvalidOperationException:
   at PortabilityService.CompressionDelegatingHandler.ParseEncodingString (CompressionDelegatingHandler.cs: 86)
   at PortabilityService.CompressionDelegatingHandler+<SendAsync>d__0.MoveNext (CompressionDelegatingHandler.cs)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
   at System.Web.Http.HttpServer+<SendAsync>d__0.MoveNext
```

**Comment by Lxiamail** [comment]
Fixed by Connie.
