### ISSUE TITLE
Incompatibilities with Type are propagated to TypeInfo

### ISSUE THREAD

**Issue by rogancarr** [Microsoft/dotnet-apiport#455]
`Type.Assembly` is not supported by `".NET Core + Platform Extensions,Version=v1.0"`. The recommended fix is `".GetTypeInfo().Assembly."`

When this fix is implemented, the ApiPort application still reports an issue on ` "M:System.Type.get_Assembly"`.

Here's a reproduction with a simple command-line file.

0. Check your `dotnet` version
- `dotnet --version`
(for the repro, this is `2.0.0-preview2-006497`)
1.  Create the project
- `dotnet new console`
- `dotnet restore`
2. Edit Program.cs
```
using System;
using System.Reflection;

namespace DotNet
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Type myType = typeof(int);
            string assemblyName = typeof(int).GetTypeInfo().Assembly.GetName().Name;
            Console.WriteLine($"The assemblyname of {myType.FullName} is {assemblyName}");
        }
    }
}
```
3. Run the project
- `dotnet run`
4. Note that the run was successful
```
Hello World!
The assemblyname of System.Int32 is System.Private.CoreLib
```
5. Run the ApiPort
- `.\ApiPort.exe analyze -r Json -f .\bin\Debug\netcoreapp2.0\DotNet.dll -o issues.json -t .NET Core + Platform Extensions, Version=1.0`
5. Look at the output file
```
{
  "SubmissionId": "a-guid,
  "ApplicationName": null,
  "CatalogLastUpdated": "2017-07-19T14:50:02.5251228+00:00",
  "MissingDependencies": [
    {
      "DefinedInAssemblyIdentity": "System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=a-token",
      "MemberDocId": "M:System.Type.get_Assembly",
      "TypeDocId": "T:System.Type",
      "RecommendedChanges": ".GetTypeInfo().Assembly.",
      "SourceCompatibleChange": "",
      "TargetStatus": [
        null
      ]
    }
  ],
  "UnresolvedUserAssemblies": [],
  "Targets": [
    ".NET Core + Platform Extensions,Version=v1.0"
  ],
  "BreakingChanges": [],
  "BreakingChangeSkippedAssemblies": []
}
```

As you can see, ApiPort reports an incompatibility on `Type`, when the fix to `TypeInfo` has been implemented.

**Comment by conniey** [comment]
Hey,

This is a known limitation of our catalog and is a false positive.  It is because of TypeInfo inherits from Type in the full .NET Framework and so the methods are seen as from Type but TypeInfo is not architected the same in .NET Core.  See #113 for more information.

**Comment by rogancarr** [comment]
Hi @conniey ! Thanks for the pointer!
