### ISSUE TITLE
API Port doesn't report unavailable API

### ISSUE THREAD

**Issue by terrajobst** [Microsoft/dotnet-apiport#456]
### Repro

```
mkdir test
cd test
cp C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Data.DataSetExtensions.dll
apiport analyze -f System.Data.DataSetExtensions.dll -t ".NET Standard, Version=2.0"
```

### Expected Results

APIs that `System.Data.DataSetExtensions.dll` depends on but are unavailable should be flagged. For instance, this is an internal API that is only available in .NET Framework and doesn't exist in .NET Standard:

```
M:System.Data.DataView.#ctor(System.Data.DataTable,System.Predicate{System.Data.DataRow},System.Comparison{System.Data.DataRow},System.Data.DataViewRowState)
```

### Actual Results

The report reports no missing APIs. That's incorrect.

**Comment by chlowell** [comment]
This is by design. The portability service reports the availability of only our APIs. "Our APIs" are the APIs in the catalog (see [`AnalysisEngine.FindMembersNotInTargets`](https://github.com/Microsoft/dotnet-apiport/blob/master/src/Microsoft.Fx.Portability/Analysis/AnalysisEngine.cs#L133)). The API in question is not in the catalog because it's internal.

**Comment by terrajobst** [comment]
@chlowell 

Hmm, I guess that makes sense. It just means we cannot use API Port for any of the .NET Framework binaries to understand how portable they are. Bummer. /cc @weshaggard

**Comment by weshaggard** [comment]
@chlowell I though the design was to report all missing APIs and if folks want API's that are part of their binaries to not show  up then they needed to add those binaries to the list of analyzed binaries.

The current approach seems like it will give a lot of folks a false sense of portability.

**Comment by terrajobst** [comment]
Yes, but the problem is nobody ever has a full set. For instance, most folks will not provide a directory for the framework either. So I don't think we can rely on resolution.
