### ISSUE TITLE
claims System.Reflection.TypeInfo.get_BaseType not supported in 4.6.1-4.7 when it is

### ISSUE THREAD

**Issue by eschneider999** [Microsoft/dotnet-apiport#463]
It's saying the following is not supported in 4.6.1 - 4.7

**System.Reflection.TypeInfo.get_BaseType** 

But it is supported...

[](https://msdn.microsoft.com/en-us/library/system.type.basetype(v=vs.110).aspx)

**Comment by conniey** [comment]
This is a duplicate of https://github.com/Microsoft/dotnet-apiport/issues/113.
