### ISSUE TITLE
Visual Studio extension fails to load

### ISSUE THREAD

**Issue by alinapopa** [Microsoft/dotnet-apiport#478]
VSIX fails to load on both VS2015 and VS2017.
The bug was introduced with PR #475 

CreateInstance failed for package [ApiPortVSPackage]Source: 'mscorlib' Description: Could not load file or assembly 'ApiPort.VisualStudio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4a286c3e845c3e69' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'ApiPort.VisualStudio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4a286c3e845c3e69' or one of its dependencies. The system cannot find the file specified. File name: 'ApiPort.VisualStudio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=4a286c3e845c3e69' at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark) at System.Activator.CreateInstance(String assemblyName, String typeName) at System.AppDomain.CreateInstance(String assemblyName, String typeName)

**Comment by twsouthwick** [comment]
Yup - I'm looking into it
