### ISSUE TITLE
Unclear how to test ASP.NET Core 2.0 compatibility

### ISSUE THREAD

**Issue by oising** [microsoft/dotnet-apiport#484]
I only see a checkbox for 1.0 -- am I missing something, or is this not supported. Perhaps it's rolled into .NET Core 2.0? *insert grumbling about confusing nomenclature*

**Comment by conniey** [comment]
Hey, I would suggest using the targets ".NET Core, Version=2.0" and "ASP.NET Core" then filtering out columns to only include the "Not supported" in both targets.

ASP.NET Core introduces namespace changes to Microsoft.AspNetCore.*, so you will get a lot of false negatives in terms of compatibility with ASP.NET Core.  [Reverse Package Search](packagesearch.azurewebsites.net) is a good site to use to see what the new namespace of your ASP.NET. (ie. `System.Web.Mvc.Controller` is `Microsoft.AspNetCore.Mvc.Controller`.

Also, including the `Microsoft.AspNetCore.All` metapackage will give you all the packages included by ASP.NET Core 2.0. (Further reading: [What's new in ASP.NET Core 2.0](https://docs.microsoft.com/en-us/aspnet/core/aspnetcore-2.0))

@terrajobst What steps do we need to take to add this as a target?

**Comment by oising** [comment]
Thanks @conniey - now excuse me while I read that about twenty times 😆

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
