### ISSUE TITLE
Add command to analyze .Net Standard 2 library against the missing of not implemented api by net461

### ISSUE THREAD

**Issue by moh-hassan** [microsoft/dotnet-apiport#496]
After the final release of .netstandard2, there are about 43 API not supported by .NET Framework 461 as shown in this [discussion  ](https://github.com/dotnet/standard/issues/133)
Using  a .netstandard2 library which use these APIs from within net461 projects, will raise an exception "not supported platform"
It's nice if ApiPort can help in warning for using these APIs in net461 projects.

**Comment by conniey** [comment]
@twsouthwick Is this related to #457?

**Comment by twsouthwick** [comment]
Yeah, this would fix that. For now, I would expect running the library against the .NET 4.6.1 framework would give the desired results

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
