### ISSUE TITLE
Console readme.md is out of date

### ISSUE THREAD

**Issue by rjvdboon** [Microsoft/dotnet-apiport#516]
The file docs/Console/README.md is out of date

- [x] the build command has changed. It suggests msbuild, whereas running build.cmd / build.sh should be used.
- [x] the build proxy setting script is gone (and maybe not necessary anymore)
- [x] the location of build outputs is different
- [x] the link to the privacy policy doesn't resolve (misses CLI)
- [x] the breaking changes "look here" doesn't resolve.

**Comment by twsouthwick** [comment]
Thanks, @rjvdboon  I'll take a look at that.
