### ISSUE TITLE
Localized strings in VSIX show locale information

### ISSUE THREAD

**Issue by conniey** [Microsoft/dotnet-apiport#529]
**Repro Steps**
- Set computer locale to en-CA
- Fetch dev or master branch from dotnet-apiport
- Debug ApiPort.Vsix
- Right-click on project -> Analyze Project Portability

**Actual**
![image](https://user-images.githubusercontent.com/10136526/33367125-4a7bc136-d4a2-11e7-87ad-ab51a4938d91.png)

**Expected**
Expect the strings without the language information in front (ie. en-CA is not there anymore)

**Comment by conniey** [comment]
@chlowell I think this may be attributed to your latest changes for localisation

**Comment by twsouthwick** [comment]
Do you see this in the console app as well?

**Comment by chlowell** [comment]
Good catch, we were concating the current culture.

**Comment by twsouthwick** [comment]
@chlowell can this be closed?

**Comment by chlowell** [comment]
Yes, surprised GitHub didn't do it when #532 merged.

**Comment by twsouthwick** [comment]
Maybe, but i'd still expect it to close.
