### ISSUE TITLE
dotnetportability.blob.core.windows.net  is down :(

### ISSUE THREAD

**Issue by Jalonso91** [Microsoft/dotnet-apiport#545]
**"dotnetportability.blob.core.windows.net"**  is down :(

We try install apiport on ubuntu and throw this error:

Downloading catalog.bin...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: dotnetportability.blob.core.windows.net

**Comment by conniey** [comment]
Fixed in #544 . We removed that storage location... the correct one is: https://portability.blob.core.windows.net/catalog/catalog.bin
