### ISSUE TITLE
HTML report generation is broken

### ISSUE THREAD

**Issue by conniey** [Microsoft/dotnet-apiport#548]
**Repro Steps**
Execute: `ApiPort.exe analyze -f ApiPort.exe -r HTML`
**Expected**
Generates HTML report
**Actual**
```
To learn more about how this tool works, including the data we are collecting,
go here - http://go.microsoft.com/fwlink/?LinkId=397652

Detecting assembly references                     [Done]
Analyzing compatibility                           [Failed]

There was an unknown error attempting to reach the service.  Please try again.
```
Original report: https://github.com/Microsoft/dotnet-apiport/issues/434#issuecomment-357398582

/cc: @DanielCaspers, @chlowell

**Comment by conniey** [comment]
Updates to our HTML Generation with razor is resulting in some unresolved references.

```
RazorEngine.Templating.TemplateCompilationException
  HResult=0x80131500
  Message=Errors while compiling a Template.
Please try the following to solve the situation:
  * If the problem is about missing/invalid references or multiple defines either try to load 
    the missing references manually (in the compiling appdomain!) or
    Specify your references manually by providing your own IReferenceResolver implementation.
    See https://antaris.github.io/RazorEngine/ReferenceResolver.html for details.
    Currently all references have to be available as files!
  * If you get 'class' does not contain a definition for 'member': 
        try another modelType (for example 'null' to make the model dynamic).
        NOTE: You CANNOT use typeof(dynamic) to make the model dynamic!
    Or try to use static instead of anonymous/dynamic types.
More details about the error:
 - error: (297, 54) 'Microsoft.Fx.Portability.Reports.Html.Resources.LocalizedStrings' does not contain a definition for 'TargetTypeHeader'
     - error: (299, 54) 'Microsoft.Fx.Portability.Reports.Html.Resources.LocalizedStrings' does not contain a definition for 'RecommendedChanges'
     - error: (528, 53) 'Microsoft.Fx.Portability.Reports.Html.Resources.LocalizedStrings' does not contain a definition for 'PackageIdHeader'
Temporary files of the compilation can be found in (please delete the folder): C:\Users\conniey\AppData\Local\Temp\RazorEngine_uqbowc4n.abi
```

**Comment by aboulfad** [comment]
Hello,
I have the same issue, installed latest extension from within VS2017, choosing excel alone works, choosing HTML provides this error, repo **aboulfad/zgw_searchVS**. The error text is misleading as I have latest v1.4.0.199 of the tool. Thanks.

> Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
> Copyright (C) Microsoft Corporation. All rights reserved.
> More information is available at http://go.microsoft.com/fwlink/?LinkId=506955
> 
> Detecting assembly references                      [Done]
> Analyzing compatibility                            [Failed]
> 
> There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

**Comment by conniey** [comment]
@aboulfad It should be fixed now. I pushed an update to the service an hour ago.
