### ISSUE TITLE
Unable to analyze Bitmap portability for .NET Core 2.0 and .NET Standard 2.0

### ISSUE THREAD

**Issue by vulcanlee** [Microsoft/dotnet-apiport#553]
My Visual Studio is 15.5.4
The Visual Studio extesion of .NET Portability Analyzer is version 1.4.0.199

I create a class library of .NET Framework 4.6.1 and only has following class:

```
    public class Class1
    {
        public Bitmap MyProperty { get; set; } = new Bitmap(100, 100);
    }
```

When I use .NET Portability Analyzer to generate report which say .NET Core 2.0 and .NET Standard 2.0 is 100% portability, but the `Bitmap` class is not supported by .NET Core 2.0 and .NET Standard 2.0

Following is a screen capture of this .NET Portability Analyzer report 

[https://www.screencast.com/t/c4HtskFmf](https://www.screencast.com/t/c4HtskFmf)

# **_Is it a bug ?_**

I have recorded operation process in this [Video](https://www.screencast.com/t/SpXrnTs5)

**Comment by conniey** [comment]
Thanks for reporting the issue with the catalog. System.Drawing.Bitmap should not be in the ".NET Core" or ".NET Standard" platform because you do not get it by default. 

However, it does exist in ".NET Core + Platform Extensions" target because the .NET team has released support for it in [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.5.0-preview1-25914-04).

**Comment by vulcanlee** [comment]
@conniey 

May I ask how long the bug will be corrected?

**Comment by vulcanlee** [comment]
@conniey 

What is the ".NET Core + Platform Extensions" and ".NET Standard + Platform Extensions"?

Where can I find more documentation on them?

**Comment by windperson** [comment]
May be he is mentioning the "Windows Compatibility Pack"?
https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/

**Comment by vulcanlee** [comment]
@windperson 

Thanks for your answer.

**Comment by conniey** [comment]
@vulcanlee
Unfortunately, there is no documentation for those platform targets.

The "+ Platform Extensions" targets were created by usimg the .NET compatibility pack and by through NuGet.org, finding Microsoft-owned packages that support .NETStandard, 2.0 or .NETCore, 2.0 and manually adding them to the target.

Consequently, you'll see Microsoft Azure SDK and NuGet SDK supported by those two targets.

**Comment by conniey** [comment]
@vulcanlee This should be fixed now. Things like `System.Drawing.Bitmap` should output the same supported targets as apisof.net.

* [apisof.net](https://apisof.net/catalog/System.Drawing.Bitmap)
* [ApiPort](https://portability.dot.net/api/fxapi?docId=T%3ASystem.Drawing.Bitmap)

**Comment by vulcanlee** [comment]
@conniey

I have tested my issue, this problem has fully solved, thanks for your help.
