### ISSUE TITLE
wrong System.Threading.Tasks.ValueTask`1 warning

### ISSUE THREAD

**Issue by springy76** [Microsoft/dotnet-apiport#556]
Tells me it's not available on 4.7.1

**Comment by conniey** [comment]
@springy76 
Hey, our catalog data is from: https://apisof.net/catalog/System.Threading.Tasks.ValueTask%3CTResult%3E.

@weshaggard Is this a problem with the catalog?

**Comment by conniey** [comment]
Looking more into this, I don't think it is a problem with the catalog. 
`ValueTask<T>` comes from the System.Threading.Tasks.Extensions NuGet package.  The target .NET 4.7.1 only includes APIs that are available when you have a .NET 4.7.1 project.  It does not include NuGet packages that also support .NET 4.7.1.
