### ISSUE TITLE
wrong System.Runtime.CompilerServices.IsReadOnlyAttribute warning

### ISSUE THREAD

**Issue by springy76** [Microsoft/dotnet-apiport#557]
Tells me not supported on netstandard2.

Gets inserted automatically by the compiler by using `readonly struct` and compiles fine on libs targetting netstandard2.0.

**Comment by conniey** [comment]
@springy76 This is correct. It is not available as part of the .NET Standard 2.0 surface area.  Support: 
* [apisof.net](https://apisof.net/catalog/System.Runtime.CompilerServices.IsReadOnlyAttribute)
* [docs.microsoft.com](https://docs.microsoft.com/en-ca/dotnet/api/system.runtime.compilerservices.isreadonlyattribute?view=netframework-4.7.1#Applies_to)

**Comment by springy76** [comment]
A hint to use ".NET Standard **+ Platform Extensions**" would have been helpful. Even today I'm unable to find a concrete definition of "Platform Extensions". Is it a special NuGet package? Is it a well defined set of NuGet packages? Which ones exactly? The term " in addition to other .NET ecosystem such as WCF, ASP.NET Core, FSharp, and Azure" is not very concrete.
