### ISSUE TITLE
lower percentage for net471 than for netstandard2.0

### ISSUE THREAD

**Issue by springy76** [Microsoft/dotnet-apiport#558]
As `net471` claims to be 100.0% compatible with `netstandard2.0` how can **ANY** api be RED for `net471` and GREEN for `netstandard2.0`?

I have a lib targetting `net471` (and compiling fine) which gets reported 100.00 % against `netstandard2.0` and 98.12 % against `net471`.

Please check and suppress that entirely, this makes no sense at all.

And I don't understand why external NuGet packages are seem to be checked although I only checked one lib (**not** using "_with project references_"):
![par](https://user-images.githubusercontent.com/16399318/35441646-94b3955a-02a4-11e8-81d9-6c9738b65166.JPG)

**Comment by conniey** [comment]
@springy76 Hey,

Similar to #556, APIs like [System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder](https://apisof.net/catalog/System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder%3CTResult%3E) are made available through the NuGet package, System.Threading.Tasks.Extensions and is not available in a vanilla .NET 4.7.1 project.

The reason for [Newtonsoft.Json](https://apisof.net/catalog/Newtonsoft.Json) appearing is because some of other .NET platform targets use it but is not included by default in a .NET 4.7.1 project.

The source of truth for all the portability service results are from https://apisof.net

**Comment by springy76** [comment]
I'm sorry to say but this spaghetti monster given fake truth website is making me angry all the time -- maybe it is just plain wrong or I'm too dumb to understand it -- but as I got linked to it in multiple responses to my issues here, I need an answer what I'm doing wrong.

Example: System.IO.Compression.ZipArchiveEntry.ExternalAttributes property introduced in net472.
-> https://apisof.net/catalog/System.IO.Compression.ZipArchiveEntry.ExternalAttributes

I'm using it inside a net471 non-SDK-project lib because it contains WPF für Prism and it just compiles. Hitting F12 on the member gives:

```
// Decompiled with JetBrains decompiler
// Type: System.IO.Compression.ZipArchiveEntry
// Assembly: System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// MVID: 8DBD1669-97BC-4190-9BD8-738561193741
// Assembly location: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net471\lib\System.IO.Compression.dll

using System.Collections.Generic;
using System.Text;

namespace System.IO.Compression
{
  /// <summary>Represents a compressed file within a zip archive.</summary>
  public class ZipArchiveEntry
  {
    private static readonly bool s_allowLargeZipArchiveEntriesInUpdateMode = IntPtr.Size > 4;
    private const ushort DefaultVersionToExtract = 10;
    private const int MaxSingleBufferSize = 2147483591;
    private ZipArchive _archive;
[..]
    public int ExternalAttributes
    {
      get
      {
        return (int) this._externalFileAttr;
      }
      set
      {
        this.ThrowIfInvalidArchive();
        this._externalFileAttr = (uint) value;
      }
    }
```

Now the same inside a new SDK style project library targetting net472:

```
// Decompiled with JetBrains decompiler
// Type: System.IO.Compression.ZipArchiveEntry
// Assembly: System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// MVID: 20BDAC9D-AB1B-492D-8888-B5C7D61324E0
// Assembly location: C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.IO.Compression.dll

using System.Collections.Generic;
using System.Text;

namespace System.IO.Compression
{
  /// <summary>Represents a compressed file within a zip archive.</summary>
  [__DynamicallyInvokable]
  public class ZipArchiveEntry
  {
    private const ushort DefaultVersionToExtract = 10;
    private ZipArchive _archive;
    private readonly bool _originallyInArchive;
    private readonly int _diskNumberStart;
    private ZipVersionNeededValues _versionToExtract;
    private ZipArchiveEntry.BitFlagValues _generalPurposeBitFlag;
    private ZipArchiveEntry.CompressionMethodValues _storedCompressionMethod;
[..]
    public int ExternalAttributes
    {
      get
      {
        return (int) this._externalFileAttr;
      }
      set
      {
        this.ThrowIfInvalidArchive();
        this._externalFileAttr = (uint) value;
      }
    }
```

Your source of truth does not even list such assembly in version 4.0.0.0 containing that property.

While the first project compiles fine on all dev PCs **plus** the build server, the latter just only fails on the build server with being unable to find the entire `ZipArchiveEntry` class at all:
-> https://apisof.net/catalog/System.IO.Compression.ZipArchiveEntry

WTF! How can this be? And why can't this source of truth site not tell me what NuGet package I have to reference? Migrating my project from net471 to net472 (by just changing one digit in the new style SDK project file) just made it fail on my dev machine because suddenly there was no ZipArchiveEntry class anymore. I manually had to insert a reference to a NuGet package which has been changed lastly in 2016!
-> https://www.nuget.org/packages/System.IO.Compression/
`    <PackageReference Include="System.IO.Compression" Version="4.3.0" />

I'm using newest VS 2017 15.8.2.
