### ISSUE TITLE
How to generate an api report as part of a Hosted VS2017 VSTS build definition?

### ISSUE THREAD

**Issue by lestephane** [Microsoft/dotnet-apiport#568]
Generating reports of compatibility problems as part of my CI pipeline would help me a lot
estimate a porting effort when working on a legacy project. But I'm not sure how to do that
seeing how the tools 'entry points' are within Visual Studio, using right-clicks on the project.

Is there a trick i'm not aware of?

**Comment by lestephane** [comment]
I've found a links that explains [how to use the command line version of the portability analyzer](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer#how-to-use-portability-analyzer). I'm going to check whether it's available on Hosted VS2017 VSTS build agents, and report

**Comment by conniey** [comment]
Hi. I apologise for not getting back to you sooner. 
Yes, the command-line tool may be your best option by having ApiPort.exe run the analysis command on your build output. If you use the JSON output, you could then compare it to your last build results, etc.

ie. `ApiPort.exe analyze -f Foo.dll -r JSON -t ".NET Standard,Version=2.0" -o Report1.json`
