### ISSUE TITLE
APIPort flags API as missing when override is missing

### ISSUE THREAD

**Issue by ericstj** [microsoft/dotnet-apiport#571]
For example: DirectoryInfo.FullName.

On desktop this is:
```C#
public class FileSystemInfo {
 public virtual string FullName { get; }
}
public class DirectoryInfo: FileSystemInfo {
 public override string FullName { get; }
}
```

On .NETCore this is:
```C#
public class FileSystemInfo {
 public virtual string FullName { get; }
}
public class DirectoryInfo: FileSystemInfo {
}
```

APIPort reports DirectoryInfo.FullName as missing but it is not.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
