### ISSUE TITLE
Broken link to LicenseTerms on marketplace.visualstudio.com

### ISSUE THREAD

**Issue by dhcgn** [Microsoft/dotnet-apiport#573]
> We only send .NET APIs to the service to analyze for portability. For more information, our privacy policy is [here](https://github.com/Microsoft/dotnet-apiport/blob/master/docs/LicenseTerms/Microsoft%20.NET%20Portability%20Analyzer%20Privacy%20Statement.txt).

See: https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer

The link https://github.com/Microsoft/dotnet-apiport/blob/master/docs/LicenseTerms/Microsoft%20.NET%20Portability%20Analyzer%20Privacy%20Statement.txt is broken, you will get a 404.

**Comment by conniey** [comment]
Hey @dhcgn! Thanks for noticing that. I fixed it and it should point you to the correct location now.
