### ISSUE TITLE
Make apiport available in brew/chocolatey/apt-get/yum

### ISSUE THREAD

**Issue by glennblock** [microsoft/dotnet-apiport#574]

**Comment by gep13** [comment]
We, the Chocolatey Team, are happy to help with any questions in getting this done.  @glennblock thanks for raising the issue.  /cc @ferventcoder

**Comment by twsouthwick** [comment]
Thanks for the suggestion - this would make it nice to consume. I've started looking into what it would take to generate packages.

@gep13 For chocolatey, is it best practice to have the package download a zip from somewhere or to include the whole app in the chocolatey package itself?

For other packages, it'll take some time to figure out how to best make them work as no one on this project has experience with them. If anyone watching the repo has experience generating the other packages, let me know (here or via a PM).

**Comment by gep13** [comment]
@twsouthwick both available are perfectly acceptable.  In terms of creating the most resilient package (i.e. one that will always work, rather than being reliant on a download), embedding the installers/files into the Chocolatey Package would be the best option.  Assuming the license permits that type of distribution, that would be my recommendation.

**Comment by gep13** [comment]
@twsouthwick I wasn't directly involved in it's creation, but we (the Cake Team) created a Homebrew package for Cake.  You can find the formula that we created here:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/cake.rb

Depending on the complexity of the application, you might be able to use the above as a guide.

**Comment by glennblock** [comment]
We created one for scriptcs as well. Basically the formula runs a build
script which should create the binaries and run unit tests. It will also
create a shell script to execute the command (dotnet apiport). One thing
for this to work is dotnet core needs to be a brew dependency.

Here is ours which depended on mono:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/scriptcs.rb

**Comment by Lxiamail** [comment]
Looks like making [ApiPort client tool .NET core version to use global tools](https://github.com/microsoft/dotnet-apiport/issues/668) will address the same issue.

**Comment by Lxiamail** [comment]
using #668 to track the issue.
