### ISSUE TITLE
Missing information in JSON report

### ISSUE THREAD

**Issue by santiaago** [microsoft/dotnet-apiport#588]
Version: `2.4.0-alpha.933`

When using APIPort to generate a JSON report I don't get the information I was expecting.

Build a hello world console application

```bash
dotnet new console -n HelloWorld
cd HelloWorld/
dotnet restore
dotnet build
```

## JSON report

When running the ApiPort to generate a JSON report:

```bash
dotnet ApiPort.dll analyze -f ./HelloWorld/bin/Debug/netcoreapp2.0/ -r JSON
```

I get the following content:

```json
{
  "SubmissionId": "042e1393-25c9-4b6a-8b2c-629ec842c045",
  "ApplicationName": "",
  "CatalogLastUpdated": "2018-03-06T15:41:30.3267612+00:00",
  "MissingDependencies": [],
  "UnresolvedUserAssemblies": [],
  "Targets": [
    ".NET Core,Version=v2.0",
    ".NET Framework,Version=v4.7.1",
    ".NET Standard,Version=v2.0"
  ],
  "BreakingChanges": [],
  "BreakingChangeSkippedAssemblies": []
}
```

## HTML report

When running the ApiPort to generate an HTML report:

```bash
dotnet ApiPort.dll analyze -f ./HelloWorld/bin/Debug/netcoreapp2.0/ -r HTML
```

I get the following report

<img width="1218" alt="screen shot 2018-03-07 at 11 29 48" src="https://user-images.githubusercontent.com/825563/37090495-885014a6-21fc-11e8-9bfa-3c8876d8a7b2.png">

I would expect the JSON report to have the same information as the HTML report.

**Comment by conniey** [comment]
Currently, the JSON format returns a JSON serialized version of [AnalyzeResponse](https://github.com/Microsoft/dotnet-apiport/blob/dev/src/lib/Microsoft.Fx.Portability/ObjectModel/AnalyzeResponse.cs).

What additional information would make this seem closer? 
The one I can think of is:
* Adding a list of calling assemblies that use that API would be useful

**Comment by santiaago** [comment]
In addition to that it would be great to have the same Portability Summary information.

* list of assemblies, with the percentage of each .net version (`.NET Core, Version=2.0`, `.NET Framework, Version=4.7.1` and `.NET Standard, Version=2`
