### ISSUE TITLE
There was an unknown error code from the service: 'Forbidden'.  Please make sure you have the most up-to-date version.

### ISSUE THREAD

**Issue by screig** [Microsoft/dotnet-apiport#594]
```
Microsoft (R) .NET Portability Analyzer 1.0.0.0 (alpha)
Copyright (C) Microsoft Corporation. All rights reserved.
More information is available at http://go.microsoft.com/fwlink/?LinkId=506955

Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'Forbidden'.  Please make sure you have the most up-to-date version.
```

![capture44](https://user-images.githubusercontent.com/4292074/37587237-abac09ba-2b56-11e8-9cab-4743cb3ffb40.PNG)
![capture45](https://user-images.githubusercontent.com/4292074/37587253-b99d2216-2b56-11e8-8e69-38f6948a3836.PNG)

**Comment by conniey** [comment]
Sorry for the late response.. Forbidden is an interesting issue. If you try it again today, do you get the same response still?

We were doing some server side updates a few days ago. @twsouthwick . Do you know if there may have been any changes that would have resulted in that 403?

**Comment by screig** [comment]
Still fails.
Also is it displaying the wrong version in the console. Look at nuget package i have installed.

**Comment by screig** [comment]
Can you help with this?
What address does it go to etc?

**Comment by conniey** [comment]
All messages are sent to: https://portability.dot.net. 
If you install Fiddler, you will be able to see where the messages are being directed to and where the 403 response is coming from.
IIRC, we had enabled a feature where the VSIX would use your default system proxy for the HTTP requests...

**Comment by twsouthwick** [comment]
@screig Just saw this. Are you behind a proxy?

**Comment by conniey** [comment]
Closing due to no response.

**Comment by soumikakrishnan** [comment]
@screig @conniey @twsouthwick 
I am trying to convert a vb .net project (4.5) to .net core 2.2 and while analyzing got the same forbidden error. Have you got any updates / response regarding the above issue ?
Thanks :)
