### ISSUE TITLE
Portability Analyzer ignores build flag?

### ISSUE THREAD

**Issue by JerkerPihl** [microsoft/dotnet-apiport#602]
Some projects in a solution should not be analyzed(build) since they will break during the current setup and build will fail. Don't ignore build checkbox?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
