### ISSUE TITLE
Breaking Changes output should consider the assembly's target framework

### ISSUE THREAD

**Issue by billwert** [microsoft/dotnet-apiport#615]
When running apiport with the -b flag on a binary targeting v4.5, I was told about v4.5 breaking changes. It would be useful if it only showed breaks after the TFM of the input binary. Having to specify it would be fine also.

This looks perhaps related to #119 but a different flavor.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
