### ISSUE TITLE
"Recommended changes" should point users to Microsoft.Windows.Compatibility package where appropriate

### ISSUE THREAD

**Issue by IanKemp** [microsoft/dotnet-apiport#625]
Should you happen to have code that is using Windows-specific APIs such as the registry, event log, performance counters, etc. then ApiPort will not give you any advice on how to port that code.

But there is a [NuGet package](https://www.nuget.org/packages/Microsoft.Windows.Compatibility), Microsoft.Windows.Compatibility, that covers many of these missing APIs. Although it is prerelease, it's definitely an option that should be presented in the ApiPort report output - as these particular APIs are almost certain to be a sticking point for Windows projects trying to migrate to Standard or Core, and visibility of Microsoft.Windows.Compatibility is not great.

**Comment by twsouthwick** [comment]
@terrajobst Is the catalog marked with APIs that are available in the `Microsoft.Windows.Compatibility` pack?

**Comment by terrajobst** [comment]
The catalog does contains the packages that are part of the compat pack (they are part of the ` + Extension` groups).

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
