### ISSUE TITLE
Solution-level analysis doesn't allow for analysing of references

### ISSUE THREAD

**Issue by IanKemp** [microsoft/dotnet-apiport#631]
With the VSIX installed, right-clicking a solution gives two options: "Analyze" and "Settings". Right-clicking a project gives the same options, as well as a third: "Analyze with references".

Analysing a project's code alone is pretty much useless, because 9 times out of 10 it's the references that are the biggest issue, so not being able to analyse code + references from the solution node is a deal-breaker because it means I have to do it manually on every project in the solution... and my solution has 85 projects.

So, if we could have "Analyze with references" on a solution level in the VSIX, that would be awesome.

It would also be extremely useful if ApiPort itself could handle being passed the filename of a .csproj or .sln, which it would then walk to find all the code and references to analyse... but that is just gravy.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
