### ISSUE TITLE
Potential feature: APIPort helper when nuget resolves an assembly from a different TFM

### ISSUE THREAD

**Issue by ericstj** [microsoft/dotnet-apiport#640]
/cc @terrajobst 

See https://github.com/NuGet/Home/wiki/Enable-.NET-Core-2.0-projects-to-work-with-.NET-Framework-4.6.1-compatible-packages

When NuGet uses AssetTargetFallback to resolve an assembly from a different framework on the current one, wouldn't it be nice to have a helper that could launch API port to let a dev know how successful that might be?

Similarly it'd be nice to be able to do the same in relation to some types of exceptions like typenotfound / missingmethod / typeload.  Not sure how successful these could be, but I think the ATF/PTF use case I mention above is pretty straight forward.

**Comment by ericstj** [comment]
Not sure about an event.  There is a warning that shows up in the error list: NU1701.  Can you hook when someone double clicks that?  Alternatively can you add a right-click option to the reference node (which will have a Warning icon next to it)?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
