### ISSUE TITLE
Please update default .NET Core version to 2.1

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/dotnet-apiport#646]
2.1 will hit final release very shortly - now is the perfect time to please change the .NET Core 2.0 checkbox to default to 2.1

![image](https://user-images.githubusercontent.com/6385855/40017696-fdc1331c-576e-11e8-96b6-46d1ed50f83e.png)

@conniey

**Comment by conniey** [comment]
This has been fixed! Thanks
