### ISSUE TITLE
Update VSIX to use AsyncPackage 

### ISSUE THREAD

**Issue by conniey** [Microsoft/dotnet-apiport#667]
When uploading the VSIX, we get this warning. We should update it to use `AsyncPackage`.

## Warning from VSIX Gallery
When using the ProvideAutoLoad attribute, your package (ApiPortVS.ApiPortVSPackage) class should derive from AsyncPackage instead of Package to improve performance. Read more about using AsyncPackage here: https://aka.ms/asyncpackage.

**Comment by NullEntity** [comment]
869797ecf0eef6720310b9cee02312c906705bff involved some of this work. I tried cloning and running from dev to get a bug fix, but had issues with the background loading. Trying to run a portability analysis pretty frequently threw UnsupportedOperationExceptions from calling GetService from a background thread. I believe the issue may have been exacerbated by having 112 projects in our solution.

To at least workaround this I needed to call ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync before some VS service calls like adding the context menu items were made. I have no idea how to find out whether this is necessary without just adding it wherever the exception gets thrown.
