### ISSUE TITLE
Publish the client as a .NET Core global tool

### ISSUE THREAD

**Issue by jeremymeng** [microsoft/dotnet-apiport#668]
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

It makes it easier to consume for developers.

**Comment by conniey** [comment]
Related to #240

**Comment by terrajobst** [comment]
@Lxiamail any way we could prioritize this?

**Comment by Lxiamail** [comment]
@terrajobst I planned to work on some report related improvement work items first since we have heard some customer feedback. Have we hears customer requests for this issue? If so, we can certainly prioritize this.

**Comment by terrajobst** [comment]
The benefit of doing it this way is that customers can get updates more quickly. Many people are still confused on how to acquire it. I keep getting pinged on why it's not a Global Tool yet.

@KathleenDollard @danroth27

**Comment by Lxiamail** [comment]
@terrajobst This is definitely something that we should do soon.

**Comment by KathleenDollard** [comment]
If it is a .NET Core shared framework dll, then creating a global tool is a fairly painless process, although creating a signed build (required) may not be. 

If it is a shared framework dll already, I can help with the syntax of the CLI and naming, and with the System.CommandLine parser. With this, I think the work to create the tool will be smallish. 

If I tis not a shared framework dll, that would be a problem.

**Comment by Lxiamail** [comment]
@KathleenDollard It is not shared framework dll. It is only released in a zip file from this repo. That is the pain point that we want to address.

**Comment by Lxiamail** [comment]
@KathleenDollard is https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create the document that I should follow to create a global tool?

**Comment by KathleenDollard** [comment]
That is a good start. I am working on another document for MSFT authored tools. Here are additional comments.


  *   All .NET (Global) Tools are framework dependent executables
     *   We are working on guidelines for 2.1/3.0. Suggest testing on both and Muti-targeting
  *   Highly recommend you create your help in word or markdown first
     *   It should parallel dotnet --help
     *   I highly recommend you review this syntax with me for consistency
  *   Highly recommend you use System.CommandLine for parsing. See https://github.com/dotnet/command-line-api
     *   Jon Sequeira can answer questions
  *   Signing is required. William Li may be able to help some
  *   The package name must be prefixed with "Microsoft". You must also reserve the non-Microsoft prefixed version.

I'm happy to schedule some time with you on this. I am out Friday and next week. I come in early if you are an early person.
________________________________

**Comment by Lxiamail** [comment]
@KathleenDollard I have created a PR https://github.com/microsoft/dotnet-apiport/pull/790 for this. Somehowever I can add you as reviewer.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
