### ISSUE TITLE
Potential Feature: Generating report on the basis of application namespaces

### ISSUE THREAD

**Issue by shailesh757** [microsoft/dotnet-apiport#690]
Hi,

Is there a way where we can generate the portability summary report grouped by namespaces rather than by the assembly? That would certainly help to analyze code where there could be some code which we certainly do not want to port.

Thanks,
Shailesh

**Comment by Lxiamail** [comment]
@shailesh757 If you output the report to excel, you can sort by namespace. Does that work for you?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
