### ISSUE TITLE
If a Microsoft assembly is part of the input assemblies and has no references api port throws an error really hard to diagnose

### ISSUE THREAD

**Issue by safern** [Microsoft/dotnet-apiport#694]
If I publish a .NET Core 2.0 app and I run `analyze -f "publishDirectory"` I will not get a report and the application will fail with a hard to diagnose error like this one: 

```
Loading catalog                                   [Done]
Loading breaking changes                          [Done]
Detecting assembly references                     [Failed]

Cannot locate assembly information for System.Object. Microsoft assemblies found are:
```

Coming from here: https://github.com/Microsoft/dotnet-apiport/blob/dev/src/lib/Microsoft.Fx.Portability.MetadataReader/SystemObjectFinder.cs#L33

In order to find out what was wrong with my input directory I had to debug the code and discover this was failing whenever `System.Private.CoreLib` was passed in which doesn't have any references. 

Also if I publish an assembly using Sdk-like projects, I don't want all the Microsoft assemblies shown in my report, so I think these assemblies should be filtered out from inputAssemblies, that way it wouldn't fail, nor show the portability of Microsoft assemblies in my report.

cc: @AlexGhiondea

**Comment by silentnightwalk** [comment]
Thanks, @safern, the question already contains the answer. Lets try.

**Comment by twsouthwick** [comment]
@AlexGhiondea I don't think it'll matter. I can't fully remember why we need to find object, but I believe it was an edge case.

**Comment by twsouthwick** [comment]
@safern Can you pull the recent changes (I just merged a possible fix) and check if it solves it for you?

**Comment by safern** [comment]
Sure, I'll try it later today.

**Comment by twsouthwick** [comment]
I just tried it and it's not fixed. I think I have a fix for it though - I'll let you know

**Comment by twsouthwick** [comment]
Got a fix - the PR is open and once it passes everything I'll merge it in. It was slightly related to #699, but not entirely... similar area, but different fixes. I'll post a release (hopefully tomorrow) with the fixes available
