### ISSUE TITLE
There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

### ISSUE THREAD

**Issue by reevestrife** [Microsoft/dotnet-apiport#696]
Hi I have a bug when running the extension:
I assume I have the lastest version, since I downloaded and installed it today.

Complete Output:

> Microsoft (R) .NET Portability Analyzer 2.5.0.0
> Copyright (C) Microsoft Corporation. All rights reserved.
> About Tool http://go.microsoft.com/fwlink/?LinkId=506955
> View Privacy Statement https://privacy.microsoft.com/en-us/privacystatement
> 
> Detecting assembly references                      [Done]
> Analyzing compatibility                            [Failed]
> 
> There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version

**Comment by MichaelVach** [comment]
Same error message for me when running the VS extension.

**Comment by mikkelbu** [comment]
I got the same error. Then I waited 10 minutes and tried again and it worked, so perhaps the problem is the service being overloaded?

**Comment by twsouthwick** [comment]
There may have been an outage. I can't reproduce this. If you are able to, please reopen the issue.
