### ISSUE TITLE
Mono 5.x on VS Extension does not show.

### ISSUE THREAD

**Issue by AraHaan** [Microsoft/dotnet-apiport#700]
In a Release of 5.x Mono added support for these things missing that the report says is missing in Mono v4.5:

System.Runtime.InteropServices.OSPlatform |   |   |   |  
-- | -- | -- | -- | --
get_Windows |   |   |   |  
  |   |   |   |  
System.Runtime.InteropServices.RuntimeInformation |   |   |   |  
IsOSPlatform(System.Runtime.InteropServices.OSPlatform) |   |   |  

As such on Mono 5.x those should show as supported. As such the check box to check for it should be added to the VS 2017 Extension.

**Comment by terrajobst** [comment]
Good point. I've added Mono 5.0 to the API catalog. It should become visible within the hour. Once there, I'll close the issue.

**Comment by AraHaan** [comment]
Thanks

**Comment by AraHaan** [comment]
@terrajobst is this issue ready to close or is it not visible yet?

**Comment by AraHaan** [comment]
🤔 I do not think that Mono 5.x supports ``System.Windows.Forms.PictureBox.set_TabStop(System.Boolean)`` or ``System.Windows.Forms.PictureBox.get_TabStop()`` yet I think due to some limitations to their GUI library which is libgdiplus or gtk#. @terrajobst

**Comment by terrajobst** [comment]
It shows up now.

```
$ apiport listTargets
```

![image](https://user-images.githubusercontent.com/5169960/45832006-9b92ed00-bcb5-11e8-9faa-bd52121bcab5.png)

**Comment by terrajobst** [comment]
API Port doesn't know whether the API works or behaves the way you'd expect. All it does is check whether the API exists. And `PictureBox.TabStop` [exists in Mono since 2.0](https://apisof.net/catalog/System.Windows.Forms.PictureBox.TabStop).
