### ISSUE TITLE
Analyzing compatibility failed

### ISSUE THREAD

**Issue by Symbai** [Microsoft/dotnet-apiport#701]
Hi, I'v ran the console version on a WPF application (debug build, anycpu where 64bit preferred, .NET framework 4.7.2) and I'm getting the following error:

```
Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error attempting to reach the service.  Please try again.
```
Any idea what that is supposed to mean and what can have caused it? The target folder contains third party libraries which are obfuscated if that matters.

**Comment by twsouthwick** [comment]
This may be related to #697 fixed by #699

**Comment by twsouthwick** [comment]
Actually, that's probably not the case. Are you behind a proxy?

**Comment by Symbai** [comment]
Hi,

no proxy / no VPN.

**Comment by Symbai** [comment]
Gave it another try after a great while, this time I've used the visual studio addon (latest) and it worked out of the box. I'm closing this issue then, either its fixed already or it was a problem with standalone version.
