### ISSUE TITLE
Convert to AsyncPackage with background load

### ISSUE THREAD

**Issue by madskristensen** [Microsoft/dotnet-apiport#709]
Your extension package is currently autoloading using the [ProvideAutoload] attribute on a Package class. This is deprecated and will result in a yellow bar warning users about your extension using a suboptimal loading strategy. 

Read more about the deprecation in [this MSDN blog post](https://blogs.msdn.microsoft.com/visualstudio/2018/05/16/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/) and feel free to contact me with any questions you might have.

Thank you!

Mads Kristensen
Program Manager
Visual Studio Extensibility

**Comment by twsouthwick** [comment]
Thanks for the update. I believe we started doing this, but got side tracked with other projects. @conniey weren't you looking into this?

**Comment by twsouthwick** [comment]
Ah - we have an issue tracking this: #667 . I'll close this one and track it with that. Thanks!
