### ISSUE TITLE
Check .NET Core 3.0 by default

### ISSUE THREAD

**Issue by danmosemsft** [Microsoft/dotnet-apiport#715]
Many people are running this tool to check their Winforms/WPF apps against the upcoming .NET Core 3.0 bits. Apparently it's not on by default as I've gotten some reports without the 3.0 column. 

Can you switch it on by default?

@conniey

**Comment by conniey** [comment]
This is done now. Thanks!

**Comment by springy76** [comment]
I wonder what someone would do with the knowledge that code will compile for .NET Core 3.0?
Will it run on Linux? Maybe, most likely not.

I have the feeling this project/tool should me merged with Platform Compatibility Analyzer.

**Comment by danmosemsft** [comment]
@springy76 I can't speak for the owners of either tool. But note many times the user wants to run on Windows only. Eg., it is being commonly used right now by customers scanning their Winforms/WPF apps.

Also, the PCA needs the source code. In some cases, customers can not easily get the old source code of an assembly they rely on.
