### ISSUE TITLE
System.Runtime.CompilerServices.IsReadOnlyAttribute again

### ISSUE THREAD

**Issue by springy76** [Microsoft/dotnet-apiport#721]
I just analyzed a lib which currently targets net472 against ".NET Standard + Platform Extensions,Version=v2.0".

It fails for #ctor in System.Runtime.CompilerServices.IsReadOnlyAttribute, but links no related code in Visual Studios error list like it usually does for other unsupported members.

As there (in this case) were no further warnings and upstream dependencies I was able to just switch from net472 to netstandard2.0 and it compiled fine, even the warning is gone now. `System.Runtime.CompilerServices.IsReadOnlyAttribute` got compiled as internal class into the target assembly.

**Comment by conniey** [comment]
The root of this issue is: https://github.com/Microsoft/dotnet-apiport/issues/273. Unfortunately, we don't take into account compiler generated code and skip it.
