### ISSUE TITLE
No suggestion for compatible reflection extensions

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/dotnet-apiport#727]
Running the tool against a .NET Framework class library containing reflection methods for .NET Core target there is no suggestion for https://www.nuget.org/packages/System.Reflection.TypeExtensions.

**Comment by conniey** [comment]
Would you mind providing an example? I feel like I am missing some context. Are you suggesting that we update the "Recommended Changes"?

**Comment by Lxiamail** [comment]
@tonyhallett hope you have worked out the problem. Closing this inactive issue now. Please feel free to open it if you have more info.
