### ISSUE TITLE
Excel file has 'Header for assembly name entries' header instead of 'Assembly'

### ISSUE THREAD

**Issue by AlexGhiondea** [microsoft/dotnet-apiport#728]
Look at the 3rd column

Actual

Target type | Target member | **_Header for assembly name entries_** | .NET Core + Platform Extensions | .NET Core | .NET Framework | .NET Standard + Platform Extensions | Recommended changes
-- | -- | -- | -- | -- | -- | -- | --

Expected

Target type | Target member | **_Assembly_** | .NET Core + Platform Extensions | .NET Core | .NET Framework | .NET Standard + Platform Extensions | Recommended changes
-- | -- | -- | -- | -- | -- | -- | --

**Comment by conniey** [comment]
Oddly enough, it's inserting the .resx comment rather than the value. 🤔 Could be a potential bug

**Comment by Lxiamail** [comment]
Fixed. Need to update the service to reflect the fix.

**Comment by jingweihaha** [comment]
The bug happens again, I'm using version 2.5.0.30.

**Comment by Lxiamail** [comment]
@jingweihaha Thanks for reporting the issue. We haven't update the service to use to fixed library yet.

**Comment by jingweihaha** [comment]
![github_issue](https://user-images.githubusercontent.com/16979214/61158708-ce69d400-a4c7-11e9-9234-11a8709c6eaf.png)
 This is what I see, the third column name.

**Comment by Lxiamail** [comment]
@jingweihaha Thanks for sharing the repro
