### ISSUE TITLE
Crash executing against solution in VS 2017 15.9.4

### ISSUE THREAD

**Issue by skennedyfromfresche** [Microsoft/dotnet-apiport#733]
Running 'Analyze Assembly Portability' against our solution crashes VS2017 15.9.4. Its not clear if this as actually registered by VS as a crash as it simply restarts without a crash report dialog. 

It appears it may be an issue with our solution containing managed C++ projects but its impossible to tell as the 'Analyze Assembly Portability' is not available if you select more than one project!

We cannot remove these projects as then the solution will not build (the projects are low level dependencies) when the 'Analyze' command is issued.

**Comment by conniey** [comment]
Hey. Would you be able to go to the ActivityLog.xml and provide some details for that crash? Here's an article on how to get it: [To Examine the ActivityLog](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2017#to-examine-the-activity-log)

This might be an issue that was fixed with #731

**Comment by twsouthwick** [comment]
@skennedyfromfresche I'm not sure if I follow what the structure of the project looks like. Are you describing a project `A` that references `B`. You want to analyze `A`, but `B` is a C++/CLI? It may be a problem with our logic to discover projects... not sure if we've tested with C++/CLI

**Comment by twsouthwick** [comment]
I get the following when trying to analyze a C++/CLI project in the `Portability Analysis` output pane:

```
Failed to locate build output files.
```

Is this what you're seeing, @skennedyfromfresche? I'll take a look as to what is causing that.

**Comment by skennedyfromfresche** [comment]
I would assume that is a different issue as I only ever experienced a crash. Hence I never really got to see any output as such.

I manually updated to v2.6.0 of the Portability Analyzer and I no longer see the crash. 👍
