### ISSUE TITLE
Analyzing compatibility Failed. There was an unexpected error.  Please try again or contact apiport@microsoft.com for help.

### ISSUE THREAD

**Issue by the4u** [microsoft/dotnet-apiport#758]
hi,

in some dll's I'm taking such a error.

Analyzing compatibility                           [Failed]

There was an unexpected error.  Please try again or contact apiport@microsoft.com for help.

I'm using portability tool in offline mode and my command is like below:
C:\Users\aaaaaa\Desktop\dotnet-apiport-dev\bin\Debug\ApiPort.Offline\net461\ApiPort.exe analyze -f C:\aaaaaa\aaaaaa\aaaaaa\aaaaaa\aaaaaa\aaaaaa\bin\Debug\dllname.dll -t ".NET Standard, Version=2.0" -r Excel -o C:\aaaaaa\aaaaaa\Desktop\result.xlsx

What can be the reason of this error. I dont take this error for all dlls. In some dlls there is problem.

**Comment by Lxiamail** [comment]
@the4u Do you still have the problem? I can't repro the issue. If it still a blocking issue for you, can you look for ApiPort.log file generated as part of the run and share it with us?

**Comment by Lxiamail** [comment]
Please feel free to open the issue if it is still a problem for you. Thanks
