### ISSUE TITLE
System.Web.MVC shows as unsupported on 4.5.2+ frameworks

### ISSUE THREAD

**Issue by nalthoff** [Microsoft/dotnet-apiport#760]
I'm running the portability analyzer against a .NET framework 4.5.2 web app. If I run the analyzer against the code and target 4.5.2, i get a compatibility score of 95.66. I would expect a score of 100% since the code compiles without errors.

Some of the target types that are marked as unsupported are:

T:System.Web.Mvc.Controller
T:System.Web.Mvc.AreaRegistration
T:System.Web.Mvc.HttpGetAttribute
T:System.Web.Mvc.RouteCollectionExtensions
T:System.Web.Mvc.HandleErrorAttribute

Any idea what is happening?

**Comment by conniey** [comment]
This is similar to https://github.com/Microsoft/dotnet-apiport/issues/722. This tool reports APIs that are shipped by the .NET Framework team (ie. System.Collections.*, System.Threading.*). Unfortunately, OOB packages such as ones shipped from the ASP.NET team are not in the catalog. The catalog source is from https://apisof.net
