### ISSUE TITLE
Dubious results in portability analyzer report

### ISSUE THREAD

**Issue by rv93** [Microsoft/dotnet-apiport#761]
Hi Team, 

I generated the portability report for `4.6.2` .Net Framework project to .Net Core v2.1.

In the target I'd also checkmarked `4.6.2` just to verify it shows 100% for the same project version or not.

To my surprise, it didn't show 100% for its own version. See the screenshot below.

![image (2)](https://user-images.githubusercontent.com/13730148/54913727-68a60c00-4f19-11e9-8ee4-bda483b14070.png)

Can you please let me know in case I'm missing something ?

Thanks 
Rahul

**Comment by conniey** [comment]
https://github.com/Microsoft/dotnet-apiport/issues/760#issuecomment-466618176
This tool only includes APIs that are shipped by the .NET Framework team. Out of band SDKs aren't part of the catalog. It's a false positive. https://apisof.net is where our data comes from.
