### ISSUE TITLE
Insufficient report

### ISSUE THREAD

**Issue by ulln** [microsoft/dotnet-apiport#763]
Please tell me what happens at runtime:
- Is a PlatformNotSupportedException thrown?
- Is an API supposed to work on a specific platform?

Without that information the tool is pretty much useless and merely answers the question "will it compile".
I need to know where my application will probably fail, without executing every single line of code.

**Comment by conniey** [comment]
Hey,

Thanks for providing feedback! When we created the tool, it was meant to answer "Will it compile?" Our general use case for this tool was used for code bases where engineers had to cost out the effort for moving to new .NET platforms. So this gives a good overview of how much work it'll take to get your application to compile and what your third party dependencies are.

A tool that notifies you of PlatformNotSupported exception is:
https://docs.microsoft.com/en-us/dotnet/standard/analyzers/api-analyzer#supported-diagnostics

I hope this helps,
Connie
