### ISSUE TITLE
Is there more detail in .NET Portability Report

### ISSUE THREAD

**Issue by hueidou** [microsoft/dotnet-apiport#766]
I find and modify code by .NET Portability Report, resolved most portability problem, but some can't. Is there more detail of related code I can output in .NET Portability Report?

![](https://user-images.githubusercontent.com/712892/59406296-369d9b00-8de0-11e9-994c-33bde229e782.png)

**Comment by Lxiamail** [comment]
@hueidou From the Portability Report output that you shared, looks like the report tells that the APIs on the list is supported on .NET Core+Platform Extensions, Version=v2.2, but not supported on ASP.NETCore,Version=v2.0. It did the query for the API on http://apsof.net, got the [same result]
(https://apisof.net/catalog/Microsoft.AspNetCore.Mvc.ApplicationParts.RelatedAssemblyAttribute). Please feel free the reopen the issue of you have any more concern.
