### ISSUE TITLE
Azure SDK for .NET libraries are reported as not compatible with .NET Framework

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#770]
For Microsoft.WindowsAzure.Storage, Microsoft.IdentityModel.Clients.ActiveDirectory, both of them are released as part of Azure SDK for .NET. Looks like API Catalog included them as part of .NET Core, but not .NET Framework.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
