### ISSUE TITLE
WPF APIs are reported not supported on .NET Core+Platform Extension, but supported on .NET Core

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#771]
I guess it is because .NET Core+Platform Extension we are still use the  2.1 API catalog while .NET Core is using 3.0 API catalog. We either need to include the version in the report, not consistently using the same version for all columns.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
