### ISSUE TITLE
Recommended changes in the report are not useful

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#773]
Recommended changes in the report are either empty cells or out of update information. Apparently, due to the huge amount of .NET APIs, we won't have the capacity to keep the information up to date. We either make the recommended changes editable by developer community and hope people will contribute to the content, or remove the column from the report. The current state is not useful and misleading if the information is out of date.

**Comment by Lxiamail** [comment]
The other option is to add the recommended change at feature or technology level, such as Appdomain feature is not supported, WCF server, WF and ASP.NET Web Forms are not supported on .NET Core.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
