### ISSUE TITLE
"Unresolved assembly" or "missing assembly" in the report is confusing 

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#774]
The Missing assemblies section in the report is confusing to customer. 
May change the report section name from "Missing assemblies" to "Unresolved assembly". 
May change the "Header for assembly name entries" to "dependency assemblies not analyzed" 
May change the "Reason" to "possible Reason" with the value like "The assembly was not included in the analyzing run. It it is an assembly that you own, include it as part of the analysis. If is third party owned assembly, work with the owner to update it to .NET standard or .NET Core"
The used by column currently is empty, it may be populated by the assembly name, which reference to the listed assembly.

**Comment by martinoss** [comment]
Agree, and additionally I was confused to see everything "green" on the summary after I wanted to test the analyzer by adding EF6 to a 4.7.1 project and referencing it in a .NET Core 3.0 project (with .NET Core 3.0 checked in settings).

**Comment by Lxiamail** [comment]
@martinoss Thank you for the feedback! 
"additionally I was confused to see everything "green" on the summary", I want to make sure that I understand what you did correctly. Did you created two projects, one is 4.7.1 project referencing EF6 as a class library; another project is .NET Core 3.0 project, which reference to the 4.7.1 project?

**Comment by martinoss** [comment]
Exactly, but just for testing purposes to see what the analyzer is telling
me.

Alicia Li <notifications@github.com> schrieb am Do., 17. Okt. 2019, 18:09:

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
