### ISSUE TITLE
ApiPort release download zip file doesn't contain .NET Core version

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#778]
https://github.com/microsoft/dotnet-apiport/releases/download/2.6.0-alpha/ApiPort.zip only contains .NET Framework version, but not .NET Core version.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
