### ISSUE TITLE
Portability Analysis Results always starts empty

### ISSUE THREAD

**Issue by chlowell** [microsoft/dotnet-apiport#782]
No matter the contents of the output directory, the Portability Analysis Results window is always empty at startup. 

Cause appears to be:
1. `OptionsModel.Formats` is backed by a collection initialized empty in the `OptionsModel` ctor and evidently not updated.
1. `OptionsViewModel.Formats` is empty because it relies on `OptionsModel.Formats`
1. A list of report file extensions is built in `ServiceProvider.GetOutputViewModel` using `OptionsViewModel.Formats`, which is always empty as described above.
1. `GetOutputViewModel` returns an `OutputViewModel` including no existing reports, which the output window renders.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
