### ISSUE TITLE
Does this extension support .net 4.8?

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/dotnet-apiport#791]
Hi:

I just found out that as the following screen shot shows there is no .NET framework 4.8 anywhere in the setting. So I am wondering if this extension support .NET Framework 4.8 at all, if not when can we expect it coming to this extension? 
![Capture](https://user-images.githubusercontent.com/6314177/62164057-88d34680-b2d0-11e9-848a-0b3601fe8a3e.PNG)

**Comment by kmadof** [comment]
Well I have 4.8 
![obraz](https://user-images.githubusercontent.com/1680172/67280254-0b813180-f4cd-11e9-9dac-502501ad9ec2.png)

But this is few months later since the issue was created. Now 4.8 is available. The issue can be closed.
