### ISSUE TITLE
WPF Datagrid is not able to solve the bindings attached on Ancestor Level 

### ISSUE THREAD

**Issue by monikprabhasahu** [microsoft/dotnet-apiport#794]
In our project we found compatibility issue After installing 4.8 Run time  or after upgrading windows 10 with 1903 update .Data grid is not able to resolve the binding ,It works perfectly fine with 4.6.1.

I found the issue where ancestor level for binding is set for Level 3

**Comment by Lxiamail** [comment]
@monikprabhasahu I guess that you want to report an WPF compatibility issue. This repo is only for ApiPort tool related issue. Please use https://developercommunity.visualstudio.com/ to report WPF issue.
