### ISSUE TITLE
Have option for listing the class (and maybe line in code) of the found incompatibility.

### ISSUE THREAD

**Issue by wmanning** [microsoft/dotnet-apiport#797]
It would make it easier to do a deeper analysis of my codebase for any potential complications before making a commitment.  

As discussed here:
https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer&ssr=false#review-details

Jukka Hyvärinen
5/24/2019
Works fine, but would be much more useful if the generated report also included line numbers or at least the number of times each feature was used. It seems such an obvious requirement...
publisher-image
Microsoft
7/26/2019
Hi Jukka,
Thank you for the feedback. Yes, having the number of call sites would be helpful to determine the impact of a missing APIs. However, collecting the number of call sites will take more time to analyze. It's the trade off between functionality and performance. We may consider to add the functionality depending on the volume of this feature requests. Feel free to open an issue at https://github.com/microsoft/dotnet-apiport/issues.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
