### ISSUE TITLE
 MarkdownParser.TryParseParagraph doesn't handle the case when the content can be saved in mulitple paragraph blocks

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#802]
When the content is a long sentence or more than more lines, commonMark.NET could convert the MD content to multiple paragraph blocks. This code only capture the first block content.

private static bool TryParseParagraph(Block block, out string contents)
            {
                contents = null;

                if (block.Tag != BlockTag.Paragraph)
                    return false;

                contents = block.InlineContent.LiteralContent;

                return true;
            }

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
