### ISSUE TITLE
Microsoft.VisualBasic.Devices.ComputerInfo and .net core 3

### ISSUE THREAD

**Issue by ZonderP** [microsoft/dotnet-apiport#804]
When analyzing a project targeting .net framework 4.7.2 then the tool (latest version) reported that 
'Microsoft.VisualBasic.Devices.ComputerInfo' would be available when targeting .net core 3.
But after several hours of trying to make it work and reading in the internet about related topics I have the feeling, that this may not be true.
Since I'm new to retargeting a project from .net framework to .net core I do not have the full understanding of how all those dependencies are supposed to work and could be wrong though.

**Comment by Lxiamail** [comment]
@ZonderP https://devblogs.microsoft.com/vbteam/visual-basic-in-net-core-3-0/ may be helpful for your question. VisualBasic is not fully supported on .NET Core 3.0, but some APIs are exposed.  In this case, the ApiPort tool is correct about reporting Microsoft.VisualBasic.Devices.ComputerInfo is available on .NET Core 3.0.
