### ISSUE TITLE
Clean up locks in DependencyFinderEngine.cs

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#810]
1. [DependencyFinderEngine.cs#L65](https://github.com/microsoft/dotnet-apiport/blob/ee03621fd35575415daadd96722cfe8cd6290a83/src/lib/Microsoft.Fx.Portability.Cci/Analyzer/DependencyFinderEngine.cs#L65) and [DependencyFinderEngine.cs#L110](https://github.com/microsoft/dotnet-apiport/blob/dev/src/lib/Microsoft.Fx.Portability.Cci/Analyzer/DependencyFinderEngine.cs#L110): Consider using the overload of AddOrUpdate that takes a factory for the initial value as well, to avoid allocating the HashSet whether you use it or not.
2. [DependencyFinderEngine.cs#L78](https://github.com/microsoft/dotnet-apiport/blob/ee03621fd35575415daadd96722cfe8cd6290a83/src/lib/Microsoft.Fx.Portability.Cci/Analyzer/DependencyFinderEngine.cs#L78) and [DependencyFinderEngine.cs#L114](https://github.com/microsoft/dotnet-apiport/blob/dev/src/lib/Microsoft.Fx.Portability.Cci/Analyzer/DependencyFinderEngine.cs#L114): Consider removing this lock. ConcurrentDictionary ensures that updates to the values done in the factories are "atomic".

Reference to PR review comments at https://github.com/microsoft/dotnet-apiport/pull/809

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
