### ISSUE TITLE
DGML reference assembly APICounts issues

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#813]
1. When a note.UsageData is null, the remaining nodes in the reference graph was skipped. Reference to Marklio's CR comment at PR https://github.com/microsoft/dotnet-apiport/pull/809.
2. The _searchInGraph reset logic is wrong. It only detects cycle reference, but duplicates counting when a node shows up in more than one branches in the reference graph.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
