### ISSUE TITLE
This is a fragile way to do this. The location of types isn't set, particularly in Core. If we want to be explicit about references, we should just build the explicit list.

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#816]
This is a fragile way to do this. The location of types isn't set, particularly in Core. If we want to be explicit about references, we should just build the explicit list.

_Originally posted by @marklio in https://github.com/microsoft/dotnet-apiport/pull/809_

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
