### ISSUE TITLE
The version and platform specific code seems not necessary and still could fails to meet the need of Ignore case comparison.

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#817]
The version and platform specific code seems not necessary and still could fails to meet the need of Ignore case comparison.

_Originally posted by @Lxiamail in https://github.com/microsoft/dotnet-apiport/pull/809_

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
