### ISSUE TITLE
On vsixgallery.com, links to documentation are broken

### ISSUE THREAD

**Issue by akeeton** [microsoft/dotnet-apiport#818]
The documentation links on http://vsixgallery.com/extension/55d15546-28ca-40dc-af23-dfa503e9c5fe are broken.

For example, the link named ".NET Portability Analyzer (Visual Studio extension)" goes to https://raw.githubusercontent.com/microsoft/dotnet-apiport/master//docs/VSExtension, which gives a 404.

**Comment by Lxiamail** [comment]
Thanks for reporting the issue. Yes, they are broken. In the meantime, you may use https://github.com/microsoft/dotnet-apiport/ document to work around the issue.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
