### ISSUE TITLE
Api Port CLi tool License

### ISSUE THREAD

**Issue by tsubhojit** [microsoft/dotnet-apiport#819]
I had a look at the ApiPort software and I think license for this tool is MIT licence which is okay, but I am concerned that there is also a Microsoft License distributed with the download that is more restrictive. 
Can you provide some more insights into this license ,"Microsoft .NET portability Analyzer CLI Prerelease License term" ??

**Comment by Lxiamail** [comment]
@tsubhojit The "Microsoft .NET portability Analyzer CLI Prerelease License term" is for binary distribution. MIT licence is for source distribution. Do you have any scenario need to distribute apiport binaries?

**Comment by Lxiamail** [comment]
closing the issue for now. Please let us know if there is anything that we can help.
