### ISSUE TITLE
.NET Core self-contain apiport app doesn't work with localhosted Portability service

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#825]
running the portability service under debugging, we can observe that basic endpoints can't be reached, like ResultFormatController.GetDefault(). 
The same self-contain apiport app works fine with public portable service. And the net461 and netcoreapp2.1 apiport app built out of the same codebase as the self-contained app works fine with localhosted service.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
