### ISSUE TITLE
advice on "unsupported" APIs

### ISSUE THREAD

**Issue by jol64** [microsoft/dotnet-apiport#832]
I ran portability analyzer today, and in essence it spotted usage of the follwing methods being non portable:

- M:System.IO.DirectoryInfo.GetAccessControl
- M:System.IO.DirectoryInfo.SetAccessControl(System.Security.AccessControl.DirectorySecurity)
- M:System.IO.Pipes.NamedPipeServerStream.#ctor(System.String,System.IO.Pipes.PipeDirection,System.Int32,System.IO.Pipes.PipeTransmissionMode,System.IO.Pipes.PipeOptions,System.Int32,System.Int32,System.IO.Pipes.PipeSecurity,System.IO.HandleInheritability,System.IO.Pipes.PipeAccessRights)
- M:System.IO.Pipes.PipeStream.GetAccessControl
- M:System.IO.Pipes.PipeStream.SetAccessControl(System.IO.Pipes.PipeSecurity)

I´d definitley expect security aspects to be covered in "Platform Extensions" aka "Windows Compatibility Pack". Is this an issue in analyzer or where can I ask a question to the "Windows Compatibility Pack"?

Thanks, Joachim

**Comment by Lxiamail** [comment]
@terrajobst Can you advice what's the recommended change for these APIs on .NET Core?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
