### ISSUE TITLE
There was an unknown error attempting to reach the service. => Certificate expired ?

### ISSUE THREAD

**Issue by iceblurr** [microsoft/dotnet-apiport#842]
After installing the NET Portability Anaylzer extension in VS 2019 16.4.0, I am having issues analyzing my projects, as it is displaying the following error :
There was an unknown error attempting to reach the service.  Please try again.

Looking into the previous issues, it seems it happened before (https://github.com/microsoft/dotnet-apiport/issues/528). 
Seeing as the issue mentioned that the extension is trying to reach this URI https://portability.dot.net/, I tried to reach it too, but it seems like the certificate expired 2 days ago, on Dec 07 2019

Could you look into it ?

**Comment by gimbus109** [comment]
Same problem on Linux - "The remote certificate is invalid according to the validation procedure"

**Comment by satheeshkotha** [comment]
Same problem on Windows 10 - "There was an unknown error attempting to reach the service.  Please try again."

**Comment by Lxiamail** [comment]
Thank you for reporting the issue. The issue was that the renewed certificate was not added to the TLS/SSL binding of the service. The issue has been fixed. Please let us know if it works for you.

**Comment by iceblurr** [comment]
Yes, it is working again ! Thanks !

**Comment by Lxiamail** [comment]
Thanks for the confirmation!
