### ISSUE TITLE
Inherited APIs are reported as not supported

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#847]
For example, System.Type.Name is reported as not support on .NET core 2.0+. However, it is available since it is inherited from base class MemberInfo. Since ApiPort's goal is identify missing APIs in target TFM, we shouldn't report inherited APIs as missing. However, ApiPort gets the API information from APICatalog, and API Catalog is shared by multiple tools, like Apisof.net. Should Apiport builds in logic to crawl the inherits chain or API Catalog categorize the inherited APIs differently?

**Comment by AraHaan** [comment]
I would say the catalog option sounds a bit better on this one.

**Comment by Lxiamail** [comment]
@AraHaan thanks for your input!

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
