### ISSUE TITLE
System.PlatformNotSupportedException: System.DirectoryServices.AccountManagement is not supported on this platform.

### ISSUE THREAD

**Issue by jol64** [microsoft/dotnet-apiport#851]
I ported an application to .NET CORE 3.1 and the plan is to run it in a docker container on linux. Actually most of the application runs as expected, but trying to use System.DirectoryServices.AccountManagement gives me the exception:

System.PlatformNotSupportedException: System.DirectoryServices.AccountManagement is not supported on this platform.

However when I run api ananlyzer, it tells me 100% supported.
Frankely, I dislike surprises like this. 
Please advise.
Thanks, Joachim

**Comment by Lxiamail** [comment]
@jol64 Thanks for reporting the issue. ApiPort tool analyzes the .NET APIs used by app by statically analyzing the assemblies. It only can tell which .NET APIs are called and if these APIs are part of the target .NET version's public surface (exposed by .NET reference assemblies). [System.DirectoryServices.AccountManagement](https://apisof.net/catalog/System.DirectoryServices.AccountManagement)  is a public API in .NET Core 3.1, but it throws System.PlatformNotSupportedException on Linux. This won't be detected by APIPort. Instead, you can use [.NET API Analyzer ](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/api-analyzer) to detect this kind of issue.

**Comment by jol64** [comment]
Hi Alicia,
thanks for the reply. I  suggest to make it more obvious in your introduction, that ApiPort essentially checks compile time only.
Thanks for the hint to .NET API Analyzer. I ran this on the same project and got warnings about APIs that do work in my application, but System.DirectoryServices.AccountManagement was not showing a warning. I suspect I need to open an issue there to figure out why?
All in all, I am kind of lacking a single point of truth on portability..
Thanks, Joachim

**Comment by DancingCorpse** [comment]
I also meet this problem in my .NET CORE 2.2 application, my application runs on my Windows 10 machine, but it still throws the PlatformNotSupported exception "System.PlatformNotSupportedException: 'System.DirectoryServices.AccountManagement is not supported on this platform.'", the version of the package "System.DirectoryServices.AccountManagement" I used is 4.5.0, did I miss something?

**Comment by Lxiamail** [comment]
@jol64 Please open an issue at https://github.com/dotnet/platform-compat for API Analyzer doesn't report System.DirectoryServices.AccountManagement throws PlatformNotSupported exception on Linux.

**Comment by Lxiamail** [comment]
@DancingCorpse I believe that System.DirectoryServices.AccountManagement is only supported on windows, see https://github.com/dotnet/runtime/issues/14734 for the status of the supported on non-windows platforms.

**Comment by Lxiamail** [comment]
> All in all, I am kind of lacking a single point of truth on portability..

Yes, this is on our to do list, but won't be available in near future.

**Comment by DancingCorpse** [comment]
> I believe that System.DirectoryServices.AccountManagement is only supported on windows, see [dotnet/runtime#14734](https://github.com/dotnet/runtime/issues/14734) for the status of the supported on non-windows platforms.

Hi @Lxiamail, I was so confused that the System.PlatformNotSupportedException threw when my application running on Windows 10 machine, do you have any suggestions? thanks.

**Comment by jol64** [comment]
> @jol64 Please open an issue at https://github.com/dotnet/platform-compat for API Analyzer doesn't report System.DirectoryServices.AccountManagement throws PlatformNotSupported exception on Linux.

https://github.com/dotnet/platform-compat/issues/224 - did this roughly six weeks ago and no reply yet.

**Comment by Lxiamail** [comment]
@DancingCorpse I see. In that case, I'm wondering if System.DirectoryServices.AccountManagement may not be fully implemented on 4.5.0 package. Have you tried https://www.nuget.org/packages/System.DirectoryServices.AccountManagement/ the latest NuGet package (4.7.0)? If you still have the same problem with 4.7.0, I would suggest you to follow up with the [dotnet/runtime#14734](https://github.com/dotnet/runtime/issues/14734) or open a new issue in  https://github.com/dotnet/runtime repo.

**Comment by DancingCorpse** [comment]
@Lxiamail, got it, thanks.
