### ISSUE TITLE
Why does Npgsql, which supports .NET Standard 2.0 and 2.1, show up with red X's in ".NET Standard + Platform Extensions,Version=v2.0"

### ISSUE THREAD

**Issue by KirkMunro** [microsoft/dotnet-apiport#852]
When analyzing my projects, including projects I have converted to .NET Standard already that use the [Npgsql](https://www.nuget.org/packages/Npgsql/) Nuget package, all references to npgsql show up as red X's, yet the package supports .NET Standard 2.0 and 2.1, as per their documentation and the Nuget package page. Is this just a bug in the analyzer, with it not properly identifying the support that this package offers?

**Comment by Lxiamail** [comment]
@KirkMunro Can you share the ApiPort generated report file and partial snapshot?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
