### ISSUE TITLE
Reports unsupported methods in Newtonsoft & SharpZip

### ISSUE THREAD

**Issue by ghost** [microsoft/dotnet-apiport#853]
Te tool is listing the following errors:

T:ICSharpCode.SharpZipLib.Zip.ZipFile | T:ICSharpCode.SharpZipLib.Zip.ZipFile
-- | --
T:ICSharpCode.SharpZipLib.Zip.ZipFile | M:ICSharpCode.SharpZipLib.Zip.ZipFile.#ctor(System.IO.FileStream)
T:Newtonsoft.Json.Linq.JObject | T:Newtonsoft.Json.Linq.JObject
T:Newtonsoft.Json.Linq.JObject | M:Newtonsoft.Json.Linq.JObject.Parse(System.String)

But the code compiles just fine (see attached). Is this a false positive? Or is Visual Studio incorrectly compiling it without an error? (Or do I not understand something about all this?)
[ApiPortAnalysis.xlsx](https://github.com/microsoft/dotnet-apiport/files/4246833/ApiPortAnalysis.xlsx)
[SampleApp.ZIP](https://github.com/microsoft/dotnet-apiport/files/4246836/SampleApp.ZIP)

**Comment by Lxiamail** [comment]
@DavidThi808 The ApiPort tool currently has the limitation of only reporting if APIs are available in .NET Core core package. In these cases, doesn't analyze other NuGet packages beyond .NET Core core packages. Both ICSharpCode and Newtonsoft have .NET Core supported Nuget packages, but they are not released as part of .NET Core framework meta packages, but they were part of the .NET Core or Mono framework in some previous .NET versions. This is why they showed up on the report as not supported on .NET Core 3.*+ . I know it is very confusing to customer, and it is something we need to better define and resolve moving forward. Thank you for reporting the issue.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
