### ISSUE TITLE
Add option to treat EditorBrowsable attribute as meaning api isn't available

### ISSUE THREAD

**Issue by mconnew** [microsoft/dotnet-apiport#855]
WCF has applied the `EditorBrowsable` attribute with `EditorBrowsableState.Never` to hide some api's which we can never support but are in our contracts for historical reasons. These methods (mostly constructors) will throw `PlatformNotSupportedException` if used. Recently with an internal team we were working with to port their usage over to .NET Core, they didn't realize that they had more work to do as the api port tool didn't flag these api's.  
It would be nice to have an option to include api's with this attribute applied as potential porting problems.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
