### ISSUE TITLE
Reports unsupported .Net Core 3.1 issues with Microsoft.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by ghost** [microsoft/dotnet-apiport#857]
It reports a bunch of use of this package as not supported in .Net Core. But in a .Net Core project I can pull it down with NuGet, compile, and run with no problem.

Let me know if you need examples.

**Comment by Lxiamail** [comment]
@terrajobst Microsoft.IdentityModel.Clients.ActiveDirectory is shown as supported on .NET Core + Platform Extensions 2.0 and 2.1 and .NET Standard + Platform Extensions 1.6 and 2.0, but no later version of .NET Core.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
