### ISSUE TITLE
how many calls an .NET API was usage is not report by APIPort tool

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#858]
ApiPort tool reports .NET APIs are called and not supported in target version of .NET. However it doesn't report how many times the API is call. Knowing the API is called only 1 time vs 100 times can help estimate the migration cost of moving to the target .NET version.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
