### ISSUE TITLE
Json format APIPort report doesn't include the analyzed assemblyname

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#861]
Below is an example of reported missing API. The assembly name, which calls the API is not on the report. This is reported by a customer. They have a large portfolio of 800+ apps running on our Azure Pack Private cloud (on premises) and they like the programmatic process the reports on Json format.
"MissingDependencies":  [
                                {
                                    "DefinedInAssemblyIdentity":  "System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
                                    "MemberDocId":  "T:System.Web.Routing.UrlRoutingHandler",
                                    "TypeDocId":  null,
                                    "RecommendedChanges":  "",
                                    "SourceCompatibleChange":  "",
                                    "TargetStatus":  [
                                                         null,
                                                         null
                                                     ]
                                },

**Comment by timotei** [comment]
@Lxiamail is this on the roadmap? If not, I will try working on it, since I need it as well.

**Comment by Lxiamail** [comment]
@timotei It would be great if you like to contribute to this!

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
