### ISSUE TITLE
Will the dotnet-apiport support to run with .Net core3.1 and target to .Net core3.1

### ISSUE THREAD

**Issue by jamoGe** [microsoft/dotnet-apiport#867]
hello ,my friend:
    I'm trying to use dotnet-apiport to profile my project which was developed with .Net Core2.1.
    It seems that dotnet-apiport can't run with .Net core 3.1 because it comes errors which says needed .Net Core 2.0.
    Also, do you have a plan about when to support target to .Net core 3.1?

best regards

**Comment by twsouthwick** [comment]
If you're project targets .NET Core 2.1, I'm not certain you'll find any help with the ApiPort. It is designed to be used to identify potential problems porting from .NET Framework to .NET Core.

As for targeting .NET Core 3.1, probably at some point (LTS for .NET Core 2.1 is until August 2021), but no plans currently.

**Comment by Lxiamail** [comment]
@jamoGe Even though APIPort tool doesn't run on .NET Core 3.1 yet, but you should be able to use it to analyze your app, which built on .NET Core 2.1, targeting .NET Core 3.1 by using command like: apiport analyze -f <your app filename> -t ".NET Core, version=3.1"

**Comment by twsouthwick** [comment]
#904 changed ApiPort command line to target .NET Core 3.1
