### ISSUE TITLE
The Visual Studio Extension makes it hard to manage reports

### ISSUE THREAD

**Issue by martingbrown** [microsoft/dotnet-apiport#868]
This is a bit of usability issue, I'm trying to sort out an assembly and have been running a report using the Visual Studio Extension and then changing some code then running another report in a loop. Each time it is creating a file with the same name and a number appended. At some point I deleted the files and ran another analysis. The Portability Analysis Results pane now has three files listed with the same name and I've no idea which is the one I want.

![image](https://user-images.githubusercontent.com/5264795/79589505-6935b580-80cd-11ea-94f9-4a4944c78a6a.png)

It would be handy if these were somehow named after the Project I ran the analysis against and included the date and time generated.

**Comment by Lxiamail** [comment]
@martingbrown thank you for reporting the issue. Displaying 3 times with the same file name looks like a bug in the tool.
Your usability comment makes sense. Attaching a number to the filename was for make the new file destined from previous files and showing the timeline sequence of files were generated. Using date and time can be another alternate solution. However, it would be low priority.

**Comment by martingbrown** [comment]
If it is just starting at zero and incrementing by one until it finds a file name that's free, that isn't going to show the correct creation sequence.

Suppose I run the tool four times then delete the first two files then run the tool a twice more. The file with no number an the file numbered 1 would actually be newer than files 2 and 3.

Another possibility is to just show the created date that windows attaches to all files.

**Comment by Lxiamail** [comment]
> If it is just starting at zero and incrementing by one until it finds a file name that's free, that isn't going to show the correct creation sequence.

Definitely. We should keep this in mind when fixing the problem.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
