### ISSUE TITLE
How to run the ApiPort tool from macOS ?

### ISSUE THREAD

**Issue by syberkitten** [microsoft/dotnet-apiport#880]
Hi

I have a big .NET Framework project which i want to test compatability to .Net Core 3.

But I'm using MacOs with Visual Studio 2019 (for mac)

Can the ApiPort be run / compiled on an macOS? 
(this is not entirely clear from documentation....)

Getting these errors:
`
/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "PresentationCore". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (MSB3245) (ApiPort.VisualStudio.2019)

/Users/xxxxx/Documents/dev/vsprojects/dotnet-apiport/src/ApiPort/ApiPort.VisualStudio.2019/CSC: Error CS0006: Metadata file '/Users/xxx/Documents/dev/vsprojects/dotnet-apiport/bin/Debug/ApiPort.VisualStudio.Common/net461/ApiPort.VisualStudio.Common.dll' could not be found (CS0006) (ApiPort.VisualStudio.2019)

`

also the documentation only references ApiPort.exe - which is available only on windows.

So do i need a windows machine to run the tool ?

Thanks

**Comment by Lxiamail** [comment]
macOS currently is not supported

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
