### ISSUE TITLE
Portability Analyzer does not identify compatibility issues when using WinForms controls that were removed in .NET Core 3.1

### ISSUE THREAD

**Issue by supranowitz** [microsoft/dotnet-apiport#882]
For example, I have an assembly that uses ContextMenu, but the tool reports 100% compatibility with .NET Core 3.1.  ContextMenu has been removed in .NET Core 3.1 per https://docs.microsoft.com/en-us/dotnet/core/compatibility/winforms.  

Note that apisof.net also still shows this class as existing in .NET Core 3.1 (https://apisof.net/catalog/System.Windows.Forms.ContextMenu), but the Microsoft docs do show that .NET Core 3.0 is the latest version that supports this control (https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.contextmenu)

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
