### ISSUE TITLE
NuGet.config file is overridden by global NuGet.Config

### ISSUE THREAD

**Issue by bashenk** [microsoft/dotnet-apiport#888]
I was unable to get the build working due to missing System.CommandLine, until I added this line to my `<packageSources>` in my NuGet.config:
### Edit 
Turns out the issue was actually that it was using my global NuGet.Config file instead of the one in the build directory. Maybe consider adding a `--configfile ./NuGet.config` argument to the `dotnet restore` command in ./init.ps1

The error I was getting was `ApiPort depends on System.CommandLine (>= 0.1.0-e171125-2) but System.CommandLine 0.1.0-e171125-2 was not found. An approximate best match of System.CommandLine 0.3.0-alpha.20054.1 was resolved`

**Comment by Lxiamail** [comment]
@bashenk Thanks for reporting the issue. Since you already figured out a fix, do you like to submit a PR?

**Comment by bashenk** [comment]
@Lxiamail Sure, I should be able to submit one tomorrow.
