### ISSUE TITLE
Analyze NuGet package dependency 

### ISSUE THREAD

**Issue by shirishwagh83** [microsoft/dotnet-apiport#892]
We have a large project which uses a lot of NuGet dependencies. When I run the ApiPort tool all the a NuGet dependencies come up as unresolved assemblies. Is there any way to fix this issue? NuGet dependencies are part of a local NuGet repository.

**Comment by Lxiamail** [comment]
@shirishwagh83 Currently, APIPort tool doesn't support looking up local NuGet repository to resolve NuGet Package dependencies. You may work around the limitation by copying the NuGet package binaries to the same root directory as your project's binary. Then using APIPort CLI command to pass into the root directory containing all the files with option "-f".

**Comment by Lxiamail** [comment]
https://github.com/microsoft/dotnet-apiport/issues/853

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
