### ISSUE TITLE
DGML Generation Broken

### ISSUE THREAD

**Issue by eslam-a-elsawy** [microsoft/dotnet-apiport#896]
I am getting this error when trying to generate DGML
There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

Excel and HTML generation are working fine

I am using Visual Studio Enterprise 2017 ... Version 15.9.24

**Comment by david-gonzalez-pnw** [comment]
+1 

### Visual Studio Version
```
Created By: Microsoft
Date Installed: 7/9/2020
Version: 2.7.3
Microsoft Visual Studio Professional 2019
Version 16.6.3
VisualStudio.16.Release/16.6.3+30225.117
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.

ASP.NET and Web Tools 2019   16.6.954.58314
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.954.58314
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.954.58314
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.954.58314
Azure Functions and Web Jobs Tools

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

### Repo
1.  Open Options -> .NET Portability Analyzer -> General
2. Enable the DGML checkbox (only in my case)
3. Target Platforms of .NET Core 3.1 and .NET Standard 2.0 
4. Right-click project and select Analyze Project Portability (with Project References)
     - Neither Analyze Project Portability or Analyze Project Portability (with Project References) works

#### Expected
A resulting DGML to be produced or opened

#### Actual 
```
Microsoft (R) .NET Portability Analyzer 2.7.0.0
Copyright (C) Microsoft Corporation. All rights reserved.
About Tool https://aka.ms/dotnet-portabilityanalyzer
View Privacy Statement https://privacy.microsoft.com/en-us/privacystatement

Detecting assembly references                      [Done]

Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
```

**Comment by DamianSuess** [comment]
Any suggestions on what is needed to assist in fixing/debugging this issue?

**Comment by kondr1** [comment]
I have same error with any type of report =(

**Comment by pranay9th** [comment]
I am getting `There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.` even I have updated portability analyzer to latest `Tool 'upgrade-assistant' was reinstalled with the latest stable version (version '0.2.237901').`

**Comment by FilenkoAndrii** [comment]
I'm faced with the same issue for 2.7.0 and 2.8.10 versions.

```ApiPort.2.8.10>Apiport.exe analyze -f "My.dll"
Microsoft (R) API Portability Analyzer v2.8.10-alpha+3a1016693b
Copyright (C) Microsoft Corporation. All rights reserved.

This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).

To learn more about how this tool works, including the data we are collecting, visit https://aka.ms/dotnet-portabilityanalyzer.

For the full privacy statement, please visit https://privacy.microsoft.com/en-us/privacystatement

Detecting assembly references                     [Done]
Analyzing compatibility                           [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.```

**Comment by kondr1** [comment]
@Lxiamail any updates?

**Comment by Lxiamail** [comment]
Thanks for reporting the issue. Looks like something broke apiport commandline tool lately. I will look into this after I finish the high pri work item on my plate currently.

**Comment by jcnewman83** [comment]
Hi, do we have any update on what this issue is, when there may be a fix or if there is a work around? 

I have tried running the tool from VS2019 using .net 5 as the target framework with Excel as the output as I have seen that some people have got around this by selecting the excel output option, however, for me this is not working. 

Thank you in advance. :-)

**Comment by UmaSathish** [comment]
Any updates on this issue? Still the server unknown error is coming.

**Comment by Lxiamail** [comment]
While we are investigating the issue, you may work around the problem by download the apiport.offline mode app at https://github.com/microsoft/dotnet-apiport/releases/download/v2.8.10-alpha/ApiPort.2.8.25.Offline.zip. Please let us know if the work around doesn't help you.

**Comment by AlanvanderVyver** [comment]
I receive the same error from the VS 2019 extension and ApiPort with Excel or HTML targets and even while trying to analyze very simple console application.

However the offline one appears to be working.

**Comment by Lxiamail** [comment]
Update. The problem has been fixed. Please let me know if you still run into the same issue.

**Comment by Lxiamail** [comment]
Keep the issue open to track the DGML original issue.

**Comment by AlanvanderVyver** [comment]
Thank you. That works.

 

Regards,

Alan.

**Comment by georgikoemdzhiev** [comment]
I am still getting this error:

```
PS D:\_Code> ApiPort.exe analyze -r DGML -f .\Intranet\
Microsoft (R) API Portability Analyzer v2.8.10-alpha+3a1016693b
Copyright (C) Microsoft Corporation. All rights reserved.

This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).

To learn more about how this tool works, including the data we are collecting, visit https://aka.ms/dotnet-portabilityanalyzer.

For the full privacy statement, please visit https://privacy.microsoft.com/en-us/privacystatement

Detecting assembly references                     [Done]
Analyzing compatibility                           [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
```

**Comment by olivier57** [comment]
Hi,
Same here
Microsoft (R) .NET Portability Analyzer 2.8.33.57843
Copyright (C) Microsoft Corporation. All rights reserved.
About Tool https://aka.ms/dotnet-portabilityanalyzer
View Privacy Statement https://privacy.microsoft.com/en-us/privacystatement
Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]
There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

**Comment by nee-verma** [comment]
Hello,
Downloaded the tool from Market place and running on VS2017. 
https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer
It still fails when DGML output selected with the following log.
it would be great to get a fix for the same.
Thanks in advance.


Microsoft (R) .NET Portability Analyzer 2.7.0.0
Copyright (C) Microsoft Corporation. All rights reserved.
About Tool https://aka.ms/dotnet-portabilityanalyzer
View Privacy Statement https://privacy.microsoft.com/en-us/privacystatement

Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
