### ISSUE TITLE
MemoryCache is reported incompatible with netstandard2.0

### ISSUE THREAD

**Issue by zitcomdev** [microsoft/dotnet-apiport#899]
According to https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1
System.Runtime.Caching/MemoryCache should be compatible with .NET Standard 2.0.
However, running the Portability Analyzer (https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer), it is reported that it is not supported in .NET Standard 2.0 (without platform extensions).

Also tried the Microsoft.Extensions.Caching.Memory instead, with the same result.

What does this mean - is there a bug in the analyzer, or in the documentation, or am I reading it incorrectly ?

Just discovered: This also happens with Newtonsoft.Json.Linq.JObject.
How reliable is the analyzer ? How should it be used ?

**Comment by Lxiamail** [comment]
@zitcomdev  I think that Portability Analyzer's report is correct. BTW, it uses the same API data as https://apisof.net/ and [.NET API  Browser](https://docs.microsoft.com/en-us/dotnet/api/?view=dotnet-plat-ext-2.1&term=System.Runtime.Caching). 

> System.Runtime.Caching/MemoryCache should be compatible with .NET Standard 2.0.
> However, running the Portability Analyzer (https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer), it is reported that it is not supported in .NET Standard 2.0 (without platform extensions).
When Portability Analyzer reports it is not support in .NET Stardard 2.0, it means that the API is not part of .NET Stardard 2.0, which is accurate. the document at https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-3.1 states that "it can be used with: .NET Standard 2.0 or later.", which is also correct. There is subtle  difference between an API is part of .NET standard 2 vs it can be used with .NET Standard. The later means that even though the API is not part of the .NET Standard, but it doesn't reply on any API beyond .NET Standard. From customer accessing app .NET Core portability purpose, either of these two cases are good news. Hope this helps to explain what you see.

Closing the issue for now. Please feel free to reopen of you have further problem.

**Comment by zitcomdev** [comment]
But that doesn't really address the issue. The documentation says that the MemoryCache should be compatible with .NET Standard 2.0 - why does the analyzer report otherwise ? Does that mean it actually isn't compatible ? Not sure what to trust here.

**Comment by dschwartzni** [comment]
For clarity:
If I create a .NET standard 2.1 project and add the NuGet package for System.Runtime.Caching (which has a .net standard 2.1 target), can I thien use MemoryCache the same way I did in the .netframework 4.7.2?

**Comment by ericstj** [comment]
Yes, you should.  
You can see the package here: https://www.nuget.org/packages/System.Runtime.Caching/
Implementation is here: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Runtime.Caching/src

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
