### ISSUE TITLE
.NET Standard + Platform Extensions, Version 2.0 => HttpTransportBindingElement.KeepAliveEnabled marked as unsupported

### ISSUE THREAD

**Issue by thomasmiko** [microsoft/dotnet-apiport#903]
Hi,

i've one question. We have a .NET Framework 4.7 component which is currently using the following Property 

**HttpTransportBindingElement.KeepAliveEnabled**

If i'm running the Portability Analyzer with the option ".NET Standard + Platform Extensions, Version 2.0" this Property is marked as unsupported. If i'm looking at MSDN, this property is available since Platform Extensions 2.1.

Does ".NET Standard + Platform Extensions, Version 2.0" means that it will only check versus the Platform Extensions Version 2.0? If yes, is it possible to add checks vs. newer Platform Extensions?

Thanks and best regards
Thomas

**Comment by Lxiamail** [comment]
@thomasmiko This is an interesting question. To help me understand the scenario that you try to address, why you target ".NET Standard + Platform Extension" insteads of ".NET Core + PlatForm Extensions"?

**Comment by thomasmiko** [comment]
@Lxiamail In our application we have a large number of .NET Framework 4.7.2 assemblies (~ 700 assemblies) and we use technologies which are no longer available in .NET Core (like WCF). For new projects / extensions we want to use a gRPC service (.NET Core). For this we want to bring some of our core assemblies to .NET standard, so we can use them in the new .net core service and in the current .net framework 4.7.2 services / client.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
