### ISSUE TITLE
APIPort provides a link to migration documentations for not supported technical areas in .NET Core

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#912]
APIPort portability report points to the [unavailable technologies](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable) for the not supported technology areas in .NET Core. It is expect that this document contains the migration guidance to .NET Core. However some of the areas' guidance still missing. The migration document is owned by technology area owner teams. We use this issue to track the progress. 

- [ ] ASP.NET:  Looks like there is ASP.NET to ASP.NET Core migration doc at [here](https://docs.microsoft.com/en-us/aspnet/core/migration/proper-to-2x/?view=aspnetcore-3.1), just need to add a link to [unavailable technologies](https://docs.microsoft.com/en-us/dotnet/core/porting/net-framework-tech-unavailable)
- [ ] WCF: Need migration doc
- [ ] WF: Need migration doc

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
