### ISSUE TITLE
Show the absolute count of missing APIs instead of percentages on APIPort report summary page

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#913]
Currently the report shows percentages of portability, which provides no usefulness or action for customers. Instead, this should show an absolute count of the APIs without showing how it relates to their total API usage. Users often don’t know how big their assemblies are, and it doesn’t really add value. A single, concrete number can help them identify “I have x amount of APIs that I’ll need to move”

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
