### ISSUE TITLE
System.CommandLine is very out of date

### ISSUE THREAD

**Issue by twsouthwick** [microsoft/dotnet-apiport#915]
The current System.CommandLine is very out of date and there are newer builds with an updated API surface.

**Comment by twsouthwick** [comment]
See https://github.com/dotnet/command-line-api/issues/1030 for roadmap info about the library

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
