### ISSUE TITLE
This package Microsoft.Azure.Management.Automation 2.0.7 is reported as NotSupported NetStandard2 although it has a dependency with NetStandard 1.4 is this correct?

### ISSUE THREAD

**Issue by christianarg** [microsoft/dotnet-apiport#916]
This package Microsoft.Azure.Management.Automation 2.0.7 (https://www.nuget.org/packages/Microsoft.Azure.Management.Automation/2.0.7) is reported as NotSupported NetStandard2 although it has a dependency with NetStandard 1.4 is this correct?

I've installed the package a a netstandard2.0 library and it compiles with no warnings.

**Comment by Lxiamail** [comment]
https://www.nuget.org/packages/Microsoft.Azure.Management.Automation/2.0.7 only supports .NET standard 1.4, However, looks like https://www.nuget.org/packages/Microsoft.Azure.Management.Automation/3.8.1-preview supports .NET standard 2.0. Looks like APICatalog that APIPort getting .NET API information may not be up to date for this library. @safern, can you take a look?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
