### ISSUE TITLE
ApiPort tool reports unresolved binaries for files that are present in the folder that is being analyzed

### ISSUE THREAD

**Issue by hssea** [microsoft/dotnet-apiport#921]
This issue repro'ed using the latest version of the tool (API Portability Analyzer v2.7.0-alpha.3+Branch.master.Sha.91e1e4c79e975742c87ea9a1a4a59874cd1d49e6).

**Repro steps:**
- Copy a subset of binaries to a folder (in order to reduce the number of files to be displayed on the  DGML file)
- run the ApiPort tool: _apiport analyze -f "MyFolder" -r dgml -t ".NET Standard, Version=2.1"  -o "\deps.dgml"_

**Result:**
The attached files.txt shows a partial list of the files in MyFolder, and the attached PNG file shows that, even though the file is present on the folder, it's being reported back, in the DGML file, as an unresolved assembly

**Expected:**
Both files to be analyzed by the ApiPort tool

[files.txt](https://github.com/microsoft/dotnet-apiport/files/5226881/files.txt)
![unresolved](https://user-images.githubusercontent.com/29931490/93248127-496df080-f744-11ea-9bda-b62ec090060b.PNG)

**Comment by Lxiamail** [comment]
@hssea can you share the "myfolder" contained binaries with me?

**Comment by MeikelLP** [comment]
I can confirm this behaviour

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
