### ISSUE TITLE
Microsoft.VisualStudio.TestTools.UnitTesting supported in .NET Standard + PE, but not in .NET Core + PE

### ISSUE THREAD

**Issue by stogle** [microsoft/dotnet-apiport#922]
This issue relates to the .NET Protability Analyzer 2.7.0.3 extension for Visual Studio 2019 16.7.3.

I ran **Analyze Project Portability** on an MSTest project targetting .NET Framework 4.8, with the following target platforms selected: ".NET Core 3.1", ".NET Core + Platform Extensions 3.1", ".NET Standard 2.0", and ".NET Standard + Platform Extensions 2.0".

The output showed 100% compatibility with ".NET Standard + Platform Extensions 2.0", but 88.4% with the other three selected target platforms. The Details tab showed that all the incompatibilities with those platforms related to the `Microsoft.VisualStudio.TestTools.UnitTesting` namespace.

I expected ".NET Core + Platform Extensions 3.1" to support everything that ".NET Standard + Platform Extensions 2.0" supports, and more. If not, what are the recommended changes for MSTest projects porting from .NET Framework to .NET Core?

**Comment by Lxiamail** [comment]
@safern, can you check out why Microsoft.VisualStudio.TestTools.UnitTesting is not in ".NET Core + Platform Extensions 3.1"?

**Comment by rokugahanfuji** [comment]
Hello, I'm going to move .NET Framework project to .NET Core 3.1 but I just encountered this problem.
Is there any update?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
