### ISSUE TITLE
.NET Portability Analyzer 2.7.0.0 gives error in VS as well as from console application

### ISSUE THREAD

**Issue by vpatgithub** [microsoft/dotnet-apiport#925]
Hi,

I tried running .NET Portability Analyzer 2.7.0.0 from VS 2019 extension as well console application. However, I am getting errors in both scenaros.

**Running from Visual Studio 2019**

Microsoft (R) .NET Portability Analyzer 2.7.0.0
Copyright (C) Microsoft Corporation. All rights reserved.
About Tool https://aka.ms/dotnet-portabilityanalyzer
View Privacy Statement https://privacy.microsoft.com/en-us/privacystatement

Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.

I see a similar issue with VS extension reported earlier but has been closed. Can you please confirm if there are any issues with Service endpoint and if we can check the status of service end point to try again when its status is available?
https://github.com/Microsoft/dotnet-apiport/issues/388

**Running from console I am getting a different error:**

ApiPort.exe analyze -r DGML -f D:\Source\
Microsoft (R) API Portability Analyzer v2.7.0-alpha.3+Branch.master.Sha.91e1e4c79e975742c87ea9a1a4a59874cd1d49e6
Copyright (C) Microsoft Corporation. All rights reserved.

This tool analyzes .NET assemblies to determine possible problems moving between .NET platforms (such as
Windows Store, desktop, Mono, .NET Core, etc) as well as between .NET Framework versions (ie 4.x->4.y).

To learn more about how this tool works, including the data we are collecting, visit https://aka.ms/dotnet-portabilityanalyzer.

For the full privacy statement, please visit https://privacy.microsoft.com/en-us/privacystatement

Detecting assembly references                     [Done]
Analyzing compatibility                           [Failed]

There was an unknown error code from the service: 'RequestEntityTooLarge'.  Please make sure you have the most up-to-date version.

**Comment by Lxiamail** [comment]
@vpatgithub Thanks for reporting the issue. When you using VS extension, did you selected DGML format? There is a known issue with DGML format in VS extension tracked by #896. The console command error  'RequestEntityTooLarge' looks different problem. Looks like the request message size may have exceeded the IIS limit. Can you try to analyze the subset of the binaries to reduce the overall size?

**Comment by vpatgithub** [comment]
@Lxiamail - Yes, I was able to generate a report with only Excel selected using VS extension.

**Comment by Houuse** [comment]
Hi, I have the same issue even though I don't have DGML selected

```
Microsoft (R) .NET Portability Analyzer 2.7.0.0
Copyright (C) Microsoft Corporation. All rights reserved.
About Tool https://aka.ms/dotnet-portabilityanalyzer
View Privacy Statement https://privacy.microsoft.com/en-us/privacystatement

Detecting assembly references                      [Done]
Analyzing compatibility                            [Failed]

There was an unknown error code from the service: 'InternalServerError'.  Please make sure you have the most up-to-date version.
```

**Comment by Robbbbin0309** [comment]
I 'm getting this error both on vs and console, output file is selected to be json and excel. Any advice?
![image](https://user-images.githubusercontent.com/110597303/182804429-b5f40ae9-4747-423b-a5df-51c7334faf32.png)
![image](https://user-images.githubusercontent.com/110597303/182804536-0d12f4bb-690f-47f3-98c5-3998852cb66f.png)
