### ISSUE TITLE
System.EnterpriseServices.Wrapper.dll - unexpected error

### ISSUE THREAD

**Issue by suchoss** [microsoft/dotnet-apiport#952]
Hello, could you please help me with my issue?

Today I tried Apiport on our project [https://github.com/HlidacStatu/HlidacStatu](https://github.com/HlidacStatu/HlidacStatu). When I run `ApiPort.exe analyze -f .` in solution folder I am getting following error:
```
Detecting assembly references                     [Failed]

An unexpected error was encountered while parsing the metadata for the PE file located at .\packages\Microsoft.NETFramework.ReferenceAssemblies.net48.1.0.0\build\.NETFramework\v4.8\System.EnterpriseServices.Wrapper.dll.

An unexpected error was encountered while parsing the metadata for the PE file located at .\packages\Microsoft.NETFramework.ReferenceAssemblies.net472.1.0.0\build\.NETFramework\v4.7.2\System.EnterpriseServices.Wrapper.dll.
```

Many thanks!

**Comment by suchoss** [comment]
Btw. when I delete those files - It works.

**Comment by Lxiamail** [comment]
@suchoss Thank you for reporting the issue. I was able to repo the problem, and will look into it.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
