### ISSUE TITLE
-VsDevCmdPath does not exist

### ISSUE THREAD

**Issue by MeikelLP** [microsoft/dotnet-apiport#953]
I installed Visual Studio 2019 and the script is hard coded to 2017. It tells me to pass in the path via `-VsDevCmdPath`.

```ps1
Set-DevEnvironment : Could not locate: C:\Program Files (x86)\Microsoft Visual Studio\2017. Pass path to  using
parameter -VsDevCmdPath.
```

But that argument does not exist in `build.ps1`.

```
dotnet-apiport\build.ps1 : A parameter cannot be found that matches parameter name
'VsDevCmdPath'
```

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
