### ISSUE TITLE
BreakingChangeParser needs to be updated

### ISSUE THREAD

**Issue by Youssef1313** [microsoft/dotnet-apiport#954]
See https://github.com/dotnet/docs/pull/21559#discussion_r523422533 and https://github.com/dotnet/docs/pull/21664

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
