### ISSUE TITLE
500 Internal server error when trying to run portability analysis and generate DGML

### ISSUE THREAD

**Issue by lxman** [microsoft/dotnet-apiport#955]
Trying to run analysis against a 4.7.2 winforms project checking for .NET 5 and trying to generate DGML. Unchecking the DGML option allows it to work. Unfortunately the project is closed source, so will not be able to provide repro in this instance.

**Comment by rsabirov** [comment]
Duplicate of #896

**Comment by Lxiamail** [comment]
Yes, it's known issue. Close this issue and use #896  to track it.
