### ISSUE TITLE
Some non-.NET Framework assemblies are unexpectedly skipped on apiport 2.8.10

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#957]
a [new feature in 2.8.10](https://github.com/microsoft/dotnet-apiport/pull/900), which is skipping analyzing .NET Framework assemblies because analyzing and report portability of .NET Framework assemblies are not helpful for customers, but adding unnecessary noise. PublicKeyToken=31bf3856ad364e35 is one of the publickeytoken on the list to skip because it’s SilverLight .NET Framework assembly’s publickeytoken. Looks like the same public key token is also used by some of the Exchange assemblies, like Microsoft.Exchange.Net.dll. .

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
