### ISSUE TITLE
500 Internal Server Error when ApiPort runs with invalid parameter

### ISSUE THREAD

**Issue by rsabirov** [microsoft/dotnet-apiport#960]
My huge (76 projects) solution analysis is failing with "500 Internal Server Error"

Request:
```
POST https://portability.dot.net/api/analyze HTTP/1.1
Host: portability.dot.net
Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Accept-Language: en-US
Client-Type: ApiPort_Console
Client-Version: 2.8.10.4154
Accept-Encoding: gzip, deflate
Cookie: ARRAffinity=24e82c91629a726c5012dd2274d734931a0aba273c1f07202df0cd5e682d475b; ARRAffinitySameSite=24e82c91629a726c5012dd2274d734931a0aba273c1f07202df0cd5e682d475b
Content-Encoding: gzip
Content-Type: application/json
Content-Length: 13930469
```

Response:
```
HTTP/1.1 500 Internal Server Error
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000
Date: Wed, 17 Feb 2021 23:05:19 GMT
Content-Length: 0
```

Any way to avoid this?

**Comment by rsabirov** [comment]
I tried using the tool just for a single dll, but still getting the same error.

**Comment by Lxiamail** [comment]
@rsabirov can you share the commandline that you used to repro the problem?

**Comment by rsabirov** [comment]
@Lxiamail it is very easy, just run it. It fails all the time.

I just tried to create a new WinForms app using .NET Framework 4.8 and run Analyze Project Portability from VS. It is failing with the same error. 

I believe service is just down, it doesn't matter what are you analysing.

**Comment by Lxiamail** [comment]
Ha, It didn't repro when I tried to analyze apiport folder itself, but repros when analyzing files in different folder. Thank you for your report. I'm looking into it.

**Comment by Lxiamail** [comment]
Okay, I know why I got the internalserver error, I ran apiport with target parameter like `-t ".NET Core, Version=5.0"` ,  which specified target name is wrong for .NET5. After correct it as `-t ".NET, Version=5.0"`,  it works fine. I'm wondering if you ran into the same problem. If not, can you share your repro command?

**Comment by rsabirov** [comment]
@Lxiamail thanks for the prompt reply. 

You are right it seems that issue is related to target! But in my case, I specified ".NET Core, Version=3.1.*****". I didn't read that with a star you are marking the default version!

And for my reproduction steps for WinForms app it was a known issue with 505 on generating DGML files.

Why would service fail with 505 instead of just validating parameters? (Targe in this case). It would save so much time for everyone.

**Comment by Lxiamail** [comment]
Okay, it's good to know that your problem is resolved. 
> Why would service fail with 505 instead of just validating parameters? (Targe in this case). It would save so much time for everyone.
Yes, this is something that we can improve. I changed the title of this issue and use it to track this.
