### ISSUE TITLE
Variances between CLI and GUI versions of ApiPort

### ISSUE THREAD

**Issue by timrhaynes** [microsoft/dotnet-apiport#968]
I have solution with 80 projects in it. They are a mix of class library projects and ASP.NET MVC, generally targeting .NET 4.7.2

I ran portability reports targeting .NET 5, using the latest builds of the GUI and CLI analyzers. Versions 2.8.0.0 and 2.8.10 respectively.

The report from the GUI version of ApiPort lists external references.
The report from the CLI version of ApiPort does not list external references.

The GUI version also has slightly higher convertibility percentages.

I expected the GUI-generated reports to be basically identical to the CLI generated reports, but they are not. 

Is this expected behaviour?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
