### ISSUE TITLE
Port order seems backwards

### ISSUE THREAD

**Issue by MisinformedDNA** [microsoft/dotnet-apiport#969]
Sorry, if I'm missing something, but the port order seems backwards.

Assume I have to project A and B. Both are .NET 4.8 and I want to port both to .NET 5.0. Also, project A has a reference to project B.

The analysis report would say that I should update project B first. But if I migrate project B first, then I would get an error

> Project '..\ClassLibraryB\ClassLibraryB.csproj' targets 'net50'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.8'.

So I see three options:

1. Follow your guidance, but all projects will need to be done "at once", to avoid committing a broken build.
2. Follow your guidance, but use multi-targeting so everything can still build, and then remove multi-targeting.
3. Do the opposite and migrate the projects with the **most** dependencies first.

What am I missing here?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
