### ISSUE TITLE
ApiPort 2.8.10-alpha fails

### ISSUE THREAD

**Issue by mdevol** [microsoft/dotnet-apiport#972]
When I run ApiPort with the following options, analyze -t ".NET, Version 5.0" -f . -r DGML, it fails in Analyzing compatibility step with the following error message:  There was an unknown error code from the service: 'InternalServerError'.

**Comment by Lxiamail** [comment]
@mdevol the target .net version format is incorrect. Please use -t ".NET, Version=5.0" instead.
