### ISSUE TITLE
.NET Portability Analyzer VSIX causes Nerdbank.GitVersioning to load wrong version of System.Runtime.CompilerServices.Unsafe.dll

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/dotnet-apiport#977]
With [Nerdbank.GitVersioning](https://github.com/dotnet/Nerdbank.GitVersioning) 3.4.203, I get the following error when building a particular .NET Framework C# class library project in the Visual Studio Professional 2017 version 15.9.36 IDE with the  [.NET Portability Analyzer](https://marketplace.visualstudio.com/items?itemName=ConnieYau.NETPortabilityAnalyzer) 2.7.0.3 extension enabled.

The error does not occur if I disable the  .NET Portability Analyzer extension or run msbuild.exe from the command line. Also, the error does not occur when building another project in the same solution, even though both projects reference Nerdbank.GitVersioning.

```
The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'PerTypeValues`1' threw an exception. ---> System.MissingMethodException: Method not found: 'IntPtr System.Runtime.CompilerServices.Unsafe.ByteOffset(!!0 ByRef, !!0 ByRef)'.
   at System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   at System.SpanHelpers.PerTypeValues`1..cctor()
   --- End of inner exception stack trace ---
   at System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   at Nerdbank.GitVersioning.ManagedGit.GitReferenceReader.ReadReference(Stream stream)
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetHeadAsReferenceOrSha()
   at Nerdbank.GitVersioning.ManagedGit.GitRepository.GetHeadCommit(Boolean readAuthor)
   at Nerdbank.GitVersioning.Managed.ManagedGitContext..ctor(String workingDirectory, String dotGitPath, String committish)
   at Nerdbank.GitVersioning.GitContext.Create(String path, String committish, Boolean writable)
   at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
   at MSBuildExtensionTask.ContextAwareTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

The exception is thrown in the devenv.exe process. In WinDbg debugging devenv.exe, `!DumpDomain` shows System Domain, Shared Domain, and Domain 1 (Name: DefaultDomain). 

- System.Runtime.CompilerServices.Unsafe.dll from .NET Portability Analyzer has been loaded to Domain 1. That copy of System.Runtime.CompilerServices.Unsafe.dll has assembly name `System.Runtime.CompilerServices.Unsafe, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` and no Win32 resources, and **lacks** the Unsafe.ByteOffset method.
- System.Runtime.CompilerServices.Unsafe.dll from Nerdbank.GitVersioning has not been loaded, as far as I can tell. That copy of System.Runtime.CompilerServices.Unsafe.dll has assembly name `System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` and a VERSIONINFO resource (FileVersion="4.700.20.12001", ProductVersion="3.1.3+8a3ffed558ddf943c1efa87d693227722d6af094"), and **includes** the Unsafe.ByteOffset method.
- System.Memory.dll from Nerdbank.GitVersioning has been loaded to Domain 1. This references `System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, PublicKeyToken=b03f5f7f11d50a3a`.

.NET Portability Analyzer has [AssemblyRedirectResolver](https://github.com/microsoft/dotnet-apiport/blob/8c217e040e115bffbf91cdc9ac9851b5e87e7241/src/ApiPort/ApiPort.VisualStudio/AssemblyRedirectResolver.cs), which seems to completely ignore the requested assembly version. I suspect that, when System.Memory.dll references System.Runtime.CompilerServices.Unsafe version 4.0.4.1, AssemblyRedirectResolver chooses to instead load version 4.0.2.0, even though it is not compatible.

Originally reported in <https://github.com/dotnet/Nerdbank.GitVersioning/issues/607>.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
