### ISSUE TITLE
Add GitHub Codespaces configuration

### ISSUE THREAD

**Issue by szlatkow** [microsoft/dotnet-apiport#982]
- [GitHub Codespaces](https://github.com/features/codespaces) is a configurable cloud development environment available in your browser on GitHub or through Visual Studio Code.

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
