### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [microsoft/dotnet-apiport#985]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by Lxiamail** [comment]
Thanks for reporting the issue. Apiport VS extension doesn't support VS 2022 yet.

**Comment by bstordrup** [comment]
Do you have a time estimate on it?

**Comment by Lxiamail** [comment]
No, there is no time estimate on it yet.

**Comment by garfbradaz** [comment]
Anytime frame for this @Lxiamail ?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
