### ISSUE TITLE
ApiPort cannot analyze .NET Framework 2.0 assemblies

### ISSUE THREAD

**Issue by aov-mx** [microsoft/dotnet-apiport#988]
I'm getting the message `* No files were found to analyze.` with the following command line:

```
ApiPort.exe analyze -f C:\repo\packages\windows7apicodepack-shell\1.1.0\lib\Microsoft.WindowsAPICodePack.Shell.dll -t ".NET Standard, Version=2.0" -t ".NET, Version=5.0" -t ".NET + Platform Extensions, Version=5.0" -r HTML -o C:\repo\AnalysisReport.html
```

This is a file from NuGet package [WindowsAPICodePack-Shell](https://www.nuget.org/packages/WindowsAPICodePack-Shell/). The same happens if I try to analyze DLL from [WindowsAPICodePack-Core](https://www.nuget.org/packages/WindowsAPICodePack-Core/).

I can open both DLLs using ildasm.exe and see their manifest. Both are .NET Framework 2.0 assemblies, likely C++/CLI.

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
