### ISSUE TITLE
The tool should compile using NET Core precompilation directives (at least as an option)

### ISSUE THREAD

**Issue by manuelelucchi** [microsoft/dotnet-apiport#991]
Hi there,
I'm porting a big WPF app to .NET Core. Since I can't just break it until it works, I used the tool to find what's not supported and then added changes the code to something supported by core if the NETCOREAPP directive is present. I ran the tool again and nothing changed in the report, since it compiles for NET 4.7.2 without any NET Core directives, and that's a difference experience compared to trying to change the target framework and compile it. I think there should be at least an option in the tool to add the Core directives or at least let you add some custom directives
Regards, 
Manuele

**Comment by Lxiamail** [comment]
@preethikurup Is this something that you may consider in the new porting tooling experience?

**Comment by manuelelucchi** [comment]
Any news?

**Comment by manuelelucchi** [comment]
@Lxiamail any news?

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
