### ISSUE TITLE
APIScan fails in  VSEngSS-MicroBuild2019-1ES pool

### ISSUE THREAD

**Issue by Lxiamail** [microsoft/dotnet-apiport#997]
Need reconfig APIScan to run in the new VSEngSS-MicroBuild2019-1ES pool

**Comment by terrajobst** [comment]
Closing as API Port was deprecated in favor of binary analysis in [.NET Upgrade Assistant](https://github.com/dotnet/upgrade-assistant/blob/main/docs/binary_analysis.md).
